# Generated by Django 5.2 on 2026-08-12 06:28

import core.utils.encryption
import crm.models
import django.db.models.deletion
import sms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0008_alter_conversation_ai_state_alter_message_status'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('fake', 'Deterministic fake')], default='fake', max_length=16)),
                ('ownership_mode', models.CharField(choices=[('platform_managed', 'Platform managed'), ('customer_owned', 'Customer owned')], default='platform_managed', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('paused', 'Paused'), ('credential_invalid', 'Credential invalid'), ('sender_unavailable', 'Sender unavailable'), ('webhook_error', 'Webhook error'), ('disconnected', 'Disconnected')], db_index=True, default='draft', max_length=24)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('messaging_service_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('phone_number_sid', models.CharField(blank=True, max_length=64)),
                ('sender_address', models.CharField(db_index=True, max_length=64)),
                ('sender_country', models.CharField(blank=True, max_length=2)),
                ('sender_capabilities', models.JSONField(blank=True, default=list)),
                ('api_key_sid', models.CharField(blank=True, max_length=64)),
                ('api_key_secret_encrypted', core.utils.encryption.EncryptedTextField(blank=True, default='', editable=False)),
                ('auth_token_encrypted', core.utils.encryption.EncryptedTextField(blank=True, default='', editable=False)),
                ('webhook_public_key', models.CharField(default=sms.models.generate_webhook_key, editable=False, max_length=64, unique=True)),
                ('inbound_webhook_status', models.CharField(default='pending', max_length=24)),
                ('status_callback_status', models.CharField(default='pending', max_length=24)),
                ('advanced_opt_out_enabled', models.BooleanField(default=False)),
                ('allow_inbound_support', models.BooleanField(default=True)),
                ('default_language', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ'), ('en', 'EN')], default='ru', max_length=2)),
                ('supported_languages', models.JSONField(default=sms.models.default_supported_languages)),
                ('ai_mode', models.CharField(choices=[('manual', 'Manual'), ('suggest', 'Suggest'), ('autopilot', 'Autopilot')], default='manual', max_length=16)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_callback_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sms_connection', to='channels.channelconnection')),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_connections_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_audit_events', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='sms.smsconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('unknown', 'Unknown'), ('implied_support', 'Inbound support'), ('opted_in', 'Opted in'), ('opted_out', 'Opted out'), ('blocked', 'Blocked'), ('invalid', 'Invalid number')], db_index=True, default='unknown', max_length=24)),
                ('source', models.CharField(choices=[('inbound_message', 'Inbound message'), ('explicit_form', 'Explicit form'), ('provider_opt_out', 'Provider opt-out'), ('provider_opt_in', 'Provider opt-in'), ('employee', 'Employee'), ('import', 'Import')], default='inbound_message', max_length=24)),
                ('last_keyword', models.CharField(blank=True, max_length=32, validators=[crm.models.validate_plain_text])),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='sms.smsconnection')),
                ('contact_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_consents', to='crm.contactidentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_consents_updated', to='organizations.organizationmembership')),
            ],
        ),
        migrations.CreateModel(
            name='SMSOutboundAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sending', 'Sending'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='created', max_length=16)),
                ('provider_message_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('segment_count_estimated', models.PositiveSmallIntegerField(default=1)),
                ('encoding', models.CharField(default='GSM-7', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_attempts', to='sms.smsconnection')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_outbound_attempt', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_message_sid', models.CharField(db_index=True, max_length=64)),
                ('provider_status', models.CharField(max_length=24)),
                ('mapped_status', models.CharField(max_length=20)),
                ('provider_error_code', models.CharField(blank=True, max_length=32)),
                ('provider_segments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_key', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='sms.smsconnection')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_status_events', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SMSWebhookEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_message_sid', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('inbound', 'Inbound'), ('status', 'Status')], max_length=16)),
                ('event_key', models.CharField(max_length=64)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('from_address', models.CharField(blank=True, max_length=64)),
                ('to_address', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField(blank=True, max_length=10000, validators=[crm.models.validate_plain_text])),
                ('num_media', models.PositiveSmallIntegerField(default=0)),
                ('messaging_service_sid', models.CharField(blank=True, max_length=64)),
                ('opt_out_type', models.CharField(blank=True, max_length=16)),
                ('provider_status', models.CharField(blank=True, max_length=24)),
                ('provider_error_code', models.CharField(blank=True, max_length=32)),
                ('provider_segments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('redacted_error', models.CharField(blank=True, max_length=80)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_envelopes', to='sms.smsconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='smsconnection',
            index=models.Index(fields=['organization', 'status'], name='sms_smsconn_organiz_e53844_idx'),
        ),
        migrations.AddIndex(
            model_name='smsconnection',
            index=models.Index(fields=['provider', 'sender_address', 'status'], name='sms_smsconn_provide_5054dd_idx'),
        ),
        migrations.AddIndex(
            model_name='smsconnection',
            index=models.Index(fields=['messaging_service_sid', 'status'], name='sms_smsconn_messagi_1a63a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'disconnected'), _negated=True), fields=('provider', 'sender_address'), name='unique_active_sms_sender'),
        ),
        migrations.AddConstraint(
            model_name='smsconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'disconnected'), _negated=True), fields=('organization',), name='one_active_sms_connection_per_org'),
        ),
        migrations.AddIndex(
            model_name='smsauditevent',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='sms_smsaudi_organiz_c1fc08_idx'),
        ),
        migrations.AddIndex(
            model_name='smsconsent',
            index=models.Index(fields=['organization', 'state', 'updated_at'], name='sms_smscons_organiz_6cb7f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsconsent',
            constraint=models.UniqueConstraint(fields=('connection', 'contact_identity'), name='unique_sms_consent_identity'),
        ),
        migrations.AddIndex(
            model_name='smsoutboundattempt',
            index=models.Index(fields=['organization'], name='sms_smsoutb_organiz_4ef395_idx'),
        ),
        migrations.AddIndex(
            model_name='smsstatusevent',
            index=models.Index(fields=['organization', 'provider_message_sid', 'received_at'], name='sms_smsstat_organiz_3edbda_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsstatusevent',
            constraint=models.UniqueConstraint(fields=('connection', 'event_key'), name='unique_sms_status_event'),
        ),
        migrations.AddIndex(
            model_name='smswebhookenvelope',
            index=models.Index(fields=['organization', 'processing_status', 'received_at'], name='sms_smswebh_organiz_79b2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='smswebhookenvelope',
            index=models.Index(fields=['connection', 'provider_message_sid', 'event_type'], name='sms_smswebh_connect_3b1513_idx'),
        ),
        migrations.AddConstraint(
            model_name='smswebhookenvelope',
            constraint=models.UniqueConstraint(fields=('connection', 'event_key'), name='unique_sms_webhook_event'),
        ),
    ]
