# Generated by Django 5.2 on 2026-08-11 14:57

import core.utils.encryption
import crm.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0007_alter_conversation_ai_state'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mailbox_email', models.EmailField(db_index=True, max_length=320)),
                ('mailbox_email_normalized', models.EmailField(db_index=True, editable=False, max_length=320)),
                ('mailbox_name', models.CharField(blank=True, max_length=200, validators=[crm.models.validate_plain_text])),
                ('google_user_id', models.CharField(db_index=True, max_length=255)),
                ('scope_snapshot', models.JSONField(default=list)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('degraded', 'Degraded'), ('reauth_required', 'Reauthorization required'), ('disconnected', 'Disconnected')], db_index=True, default='connected', max_length=24)),
                ('automation_mode', models.CharField(choices=[('manual', 'Manual'), ('suggest', 'Suggest'), ('autopilot', 'Autopilot')], default='manual', max_length=20)),
                ('history_id', models.CharField(blank=True, max_length=64)),
                ('watch_expiration_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('watch_topic', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('last_incremental_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gmail_connection', to='channels.channelconnection')),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmail_connections_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['mailbox_email_normalized'],
            },
        ),
        migrations.CreateModel(
            name='GmailAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_audit_events', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='gmail_integration.gmailconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailMessageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('gmail_thread_id', models.CharField(db_index=True, max_length=255)),
                ('rfc_message_id', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('in_reply_to', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('references', models.TextField(blank=True, max_length=4000, validators=[crm.models.validate_plain_text])),
                ('subject', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('participants', models.JSONField(default=list)),
                ('label_ids', models.JSONField(default=list)),
                ('attachment_metadata', models.JSONField(default=list)),
                ('is_automated', models.BooleanField(default=False)),
                ('is_from_self', models.BooleanField(default=False)),
                ('is_historical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_records', to='gmail_integration.gmailconnection')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_record', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pubsub_message_id', models.CharField(max_length=255, unique=True)),
                ('history_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='received', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='gmail_integration.gmailconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('intended_redirect', models.CharField(max_length=300, validators=[crm.models.validate_plain_text])),
                ('code_verifier', core.utils.encryption.EncryptedTextField(editable=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_oauth_states', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GmailOutboundAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('provider_request_id', models.CharField(blank=True, max_length=120)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_attempts', to='gmail_integration.gmailconnection')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_outbound_attempt', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GmailSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('initial', 'Initial'), ('incremental', 'Incremental'), ('full', 'Bounded full'), ('reconciliation', 'Reconciliation')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('start_history_id', models.CharField(blank=True, max_length=64)),
                ('end_history_id', models.CharField(blank=True, max_length=64)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('ignored_count', models.PositiveIntegerField(default=0)),
                ('fallback_reason', models.CharField(blank=True, max_length=80)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='gmail_integration.gmailconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gmailconnection',
            index=models.Index(fields=['organization', 'connection_status', '-created_at'], name='gmail_integ_organiz_3c0fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailconnection',
            index=models.Index(fields=['mailbox_email_normalized', 'connection_status'], name='gmail_integ_mailbox_3728be_idx'),
        ),
        migrations.AddConstraint(
            model_name='gmailconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('connection_status__in', ['connected', 'degraded', 'reauth_required'])), fields=('mailbox_email_normalized',), name='unique_active_gmail_mailbox'),
        ),
        migrations.AddIndex(
            model_name='gmailmessagerecord',
            index=models.Index(fields=['organization', 'gmail_thread_id'], name='gmail_integ_organiz_1e70d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='gmailmessagerecord',
            constraint=models.UniqueConstraint(fields=('connection', 'gmail_message_id'), name='unique_gmail_provider_message'),
        ),
        migrations.AddIndex(
            model_name='gmailnotification',
            index=models.Index(fields=['organization', 'status', '-received_at'], name='gmail_integ_organiz_9d0b61_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailoauthstate',
            index=models.Index(fields=['organization'], name='gmail_integ_organiz_6c4ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailoutboundattempt',
            index=models.Index(fields=['organization'], name='gmail_integ_organiz_fd2a47_idx'),
        ),
    ]
