# Generated by Django 5.2 on 2026-08-11 16:07

import crm.models
import django.core.validators
import django.db.models.deletion
import gmail_integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('gmail_integration', '0001_initial'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gmailconnection',
            name='unique_active_gmail_mailbox',
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='excluded_label_ids',
            field=models.JSONField(default=gmail_integration.models.default_excluded_labels),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='included_label_ids',
            field=models.JSONField(default=gmail_integration.models.default_included_labels),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='initial_sync_cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='initial_sync_max_messages',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='initial_sync_mode',
            field=models.CharField(choices=[('from_now', 'From now'), ('recent', 'Recent messages')], default='recent', max_length=20),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='initial_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='sync_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailmessagerecord',
            name='cc_recipients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gmailmessagerecord',
            name='internal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailmessagerecord',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gmailmessagerecord',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='gmailmessagerecord',
            name='snippet',
            field=models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text]),
        ),
        migrations.AddField(
            model_name='gmailmessagerecord',
            name='to_recipients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gmailoauthstate',
            name='initial_sync_max_messages',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gmailoauthstate',
            name='initial_sync_mode',
            field=models.CharField(choices=[('from_now', 'From now'), ('recent', 'Recent messages')], default='recent', max_length=20),
        ),
        migrations.AddField(
            model_name='gmailoauthstate',
            name='reconnect_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_reconnect_states', to='gmail_integration.gmailconnection'),
        ),
        migrations.AlterField(
            model_name='gmailconnection',
            name='connection_status',
            field=models.CharField(choices=[('syncing', 'Syncing'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('reauth_required', 'Reauthorization required'), ('revoked', 'Revoked'), ('permission_missing', 'Permission missing'), ('watch_expired', 'Watch expired'), ('disconnected', 'Disconnected')], db_index=True, default='connected', max_length=24),
        ),
        migrations.AlterField(
            model_name='gmailsyncrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='gmailconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('connection_status__in', ['syncing', 'connected', 'degraded', 'reauth_required', 'revoked', 'permission_missing', 'watch_expired'])), fields=('mailbox_email_normalized',), name='unique_active_gmail_mailbox'),
        ),
    ]
