[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

; -------------------- Gunicorn (Django web) --------------------
[program:gunicorn]
command=gunicorn -b %(ENV_GUNICORN_HOST)s:%(ENV_GUNICORN_PORT)s --timeout %(ENV_GUNICORN_TIMEOUT)s --max-requests %(ENV_GUNICORN_MAX_REQUESTS)s --max-requests-jitter %(ENV_GUNICORN_MAX_REQUESTS_JITTER)s -w %(ENV_GUNICORN_WORKERS)s --limit-request-line 8190 --limit-request-fields 100 --limit-request-field_size 8190 --access-logfile - --error-logfile - --capture-output config.wsgi:application
directory=/application
autostart=true
autorestart=true
stopsignal=QUIT
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0

; -------------------- Celery Worker --------------------
[program:celery-worker]
command=celery -A config worker -l info --concurrency=2 --hostname=worker@%%h
directory=/application
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0

; -------------------- Celery Beat (schedule from settings.py) --------------------
[program:celery-beat]
command=celery -A config beat -l info
directory=/application
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
