# Generated by Django 5.2 on 2026-08-09 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccessLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=120)),
                ('contact', models.CharField(db_index=True, max_length=160)),
                ('industry', models.CharField(max_length=80)),
                ('preferred_channel', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('consent', models.BooleanField()),
                ('locale', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ'), ('en', 'EN')], max_length=2)),
                ('source', models.CharField(blank=True, default='landing', max_length=80)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['locale', 'created_at'], name='early_acces_locale_f88f99_idx')],
            },
        ),
    ]
