from django.urls import path

from crm.views import (
    ContactDetailView,
    ContactIdentityDetailView,
    ContactIdentityListView,
    ContactListCreateView,
    ContactMergeView,
    ContactNotesView,
    ConversationAssignView,
    ConversationDetailView,
    ConversationListView,
    ConversationMarkReadView,
    ConversationMessagesView,
    ConversationNotesView,
    ConversationReopenView,
    ConversationResolveView,
    CrmActivityView,
    CrmOverviewView,
    DevTestConversationView,
    FollowUpTaskDetailView,
    FollowUpTaskListCreateView,
    LeadDetailView,
    LeadLoseView,
    LeadListCreateView,
    LeadMoveView,
    LeadWinView,
    PipelineDetailView,
    PipelineListCreateView,
    PipelineStageDetailView,
    PipelineStagesView,
    TagListCreateView,
)


urlpatterns = [
    path("contacts/", ContactListCreateView.as_view(), name="contact-list"),
    path("contacts/<uuid:contact_id>/", ContactDetailView.as_view(), name="contact-detail"),
    path("contacts/<uuid:contact_id>/merge/", ContactMergeView.as_view(), name="contact-merge"),
    path("contacts/<uuid:contact_id>/identities/", ContactIdentityListView.as_view(), name="contact-identities"),
    path("contacts/<uuid:contact_id>/identities/<uuid:identity_id>/", ContactIdentityDetailView.as_view(), name="contact-identity-detail"),
    path("contacts/<uuid:contact_id>/notes/", ContactNotesView.as_view(), name="contact-notes"),
    path("tags/", TagListCreateView.as_view(), name="tag-list"),
    path("conversations/", ConversationListView.as_view(), name="conversation-list"),
    path("conversations/<uuid:conversation_id>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("conversations/<uuid:conversation_id>/messages/", ConversationMessagesView.as_view(), name="conversation-messages"),
    path("conversations/<uuid:conversation_id>/mark-read/", ConversationMarkReadView.as_view(), name="conversation-mark-read"),
    path("conversations/<uuid:conversation_id>/assign/", ConversationAssignView.as_view(), name="conversation-assign"),
    path("conversations/<uuid:conversation_id>/resolve/", ConversationResolveView.as_view(), name="conversation-resolve"),
    path("conversations/<uuid:conversation_id>/reopen/", ConversationReopenView.as_view(), name="conversation-reopen"),
    path("conversations/<uuid:conversation_id>/notes/", ConversationNotesView.as_view(), name="conversation-notes"),
    path("pipelines/", PipelineListCreateView.as_view(), name="pipeline-list"),
    path("pipelines/<uuid:pipeline_id>/", PipelineDetailView.as_view(), name="pipeline-detail"),
    path("pipelines/<uuid:pipeline_id>/stages/", PipelineStagesView.as_view(), name="pipeline-stages"),
    path("pipeline-stages/<uuid:stage_id>/", PipelineStageDetailView.as_view(), name="pipeline-stage-detail"),
    path("leads/", LeadListCreateView.as_view(), name="lead-list"),
    path("leads/<uuid:lead_id>/", LeadDetailView.as_view(), name="lead-detail"),
    path("leads/<uuid:lead_id>/move/", LeadMoveView.as_view(), name="lead-move"),
    path("leads/<uuid:lead_id>/win/", LeadWinView.as_view(), name="lead-win"),
    path("leads/<uuid:lead_id>/lose/", LeadLoseView.as_view(), name="lead-lose"),
    path("follow-up-tasks/", FollowUpTaskListCreateView.as_view(), name="task-list"),
    path("follow-up-tasks/<uuid:task_id>/", FollowUpTaskDetailView.as_view(), name="task-detail"),
    path("crm/overview/", CrmOverviewView.as_view(), name="crm-overview"),
    path("crm/activity/", CrmActivityView.as_view(), name="crm-activity"),
    path("dev/test-conversations/", DevTestConversationView.as_view(), name="dev-test-conversation"),
]
