# Generated by Django 5.2 on 2026-06-16 08:04

from django.db import migrations, models


def promote_superusers(apps, schema_editor):
    """Existing superusers become Administrators so they aren't locked out."""
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superuser=True).update(role='admin')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('operations', 'Operations User')], db_index=True, default='operations', max_length=20, verbose_name='role'),
        ),
        migrations.RunPython(promote_superusers, noop),
    ]
