# Generated by Django 5.2 on 2026-08-10 16:45

import crm.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0005_alter_conversation_ai_state_and_more'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_user_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(max_length=160, validators=[crm.models.validate_plain_text])),
                ('account_type', models.CharField(default='BUSINESS', max_length=40, validators=[crm.models.validate_plain_text])),
                ('profile_name', models.CharField(blank=True, max_length=200, validators=[crm.models.validate_plain_text])),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000)),
                ('profile_picture_expires_at', models.DateTimeField(blank=True, null=True)),
                ('graph_api_version', models.CharField(blank=True, max_length=32, validators=[crm.models.validate_plain_text])),
                ('permission_snapshot', models.JSONField(default=list)),
                ('webhook_subscription_status', models.CharField(default='pending', max_length=40)),
                ('connection_status', models.CharField(choices=[('draft', 'Draft'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('disconnected', 'Disconnected')], db_index=True, default='draft', max_length=20)),
                ('automation_mode', models.CharField(choices=[('manual', 'Manual'), ('suggest', 'Suggest'), ('autopilot', 'Autopilot')], default='manual', max_length=20)),
                ('human_agent_approved', models.BooleanField(default=False)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instagram_connection', to='channels.channelconnection')),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instagram_connections_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramConversationWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_customer_message_at', models.DateTimeField()),
                ('standard_window_expires_at', models.DateTimeField(db_index=True)),
                ('human_agent_window_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_window', to='crm.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('intended_redirect', models.CharField(max_length=300, validators=[crm.models.validate_plain_text])),
                ('nonce_hash', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_oauth_states', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramOutboundAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='queued', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('provider_request_id', models.CharField(blank=True, max_length=120)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_attempts', to='instagram.instagramconnection')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_outbound_attempt', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('professional_account_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('normalized_payload', models.JSONField(default=dict, validators=[crm.models.validate_safe_metadata])),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='received', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='instagram.instagramconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='instagramconnection',
            index=models.Index(fields=['organization', 'connection_status', '-created_at'], name='instagram_i_organiz_7b48b3_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconnection',
            index=models.Index(fields=['instagram_user_id', 'connection_status'], name='instagram_i_instagr_be4c3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='instagramconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('connection_status__in', ['draft', 'connected', 'degraded', 'expired'])), fields=('instagram_user_id',), name='unique_attached_instagram_account'),
        ),
        migrations.AddIndex(
            model_name='instagramconversationwindow',
            index=models.Index(fields=['organization', 'standard_window_expires_at'], name='instagram_i_organiz_f6ccd0_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramoauthstate',
            index=models.Index(fields=['organization', 'user_id', 'expires_at'], name='instagram_i_organiz_7ad899_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramoutboundattempt',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='instagram_i_organiz_83623f_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhookevent',
            index=models.Index(fields=['organization', 'status', '-received_at'], name='instagram_i_organiz_b62b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhookevent',
            index=models.Index(fields=['professional_account_id', 'event_type', '-received_at'], name='instagram_i_profess_0e6312_idx'),
        ),
    ]
