# Generated by Django 5.2 on 2026-08-09 17:39

import core.utils.encryption
import django.db.models.deletion
import organizations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('gmail', 'Gmail'), ('sms', 'SMS'), ('voice', 'Voice'), ('webchat', 'Web chat'), ('other', 'Other')], db_index=True, max_length=20)),
                ('provider', models.CharField(db_index=True, max_length=80)),
                ('display_name', models.CharField(max_length=160)),
                ('external_identifier', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('connecting', 'Connecting'), ('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], db_index=True, default='draft', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('encrypted_credentials', core.utils.encryption.EncryptedTextField(blank=True, default='')),
                ('webhook_secret_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_connections', to='organizations.branch')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['display_name', 'created_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'type'], name='channels_ch_organiz_7dfe52_idx'), models.Index(fields=['provider', 'type', 'external_identifier', 'status'], name='channels_ch_provide_cd1b67_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'type', 'external_identifier'), name='unique_org_channel_destination'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('provider', 'type', 'external_identifier'), name='unique_active_provider_destination')],
            },
        ),
    ]
