# Generated by Django 5.1.4 on 2026-08-14 10:46

import django.db.models.deletion
import billing.models
import organizations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_plane', '0002_version_plan_catalog'),
        ('organizations', '0002_branch_working_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('key', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('string_set', 'String set')], max_length=16)),
                ('default_value', models.JSONField(default=billing.models.default_feature_value)),
                ('enforcement_mode', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('informational', 'Informational')], default='hard', max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('default_currency', models.CharField(default='UZS', max_length=3)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('provider', models.CharField(default='manual', max_length=24)),
                ('provider_customer_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('closed', 'Closed')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BillingProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=24)),
                ('provider_event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('safe_error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_billing_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=24)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=160)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('discount_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('amount_paid_minor', models.BigIntegerField(default=0)),
                ('amount_due_minor', models.BigIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.billingaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('base', 'Base'), ('usage', 'Usage'), ('adjustment', 'Adjustment'), ('credit', 'Credit'), ('tax_placeholder', 'Tax placeholder')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('feature_or_meter_key', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=24)),
                ('unit_amount_minor', models.BigIntegerField()),
                ('amount_minor', models.BigIntegerField()),
                ('source_period', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('pricing_snapshot', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=24)),
                ('provider_payment_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('billing_interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('one_time', 'One time')], max_length=12)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('included_usage', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('overage_rates', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='control_plane.plancatalog')),
            ],
            options={
                'ordering': ['plan__key', 'plan__version', 'currency', 'billing_interval'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='manual', max_length=24)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('grace', 'Grace'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('manual', 'Manual')], db_index=True, max_length=16)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider_state', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.billingaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='control_plane.plancatalog')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.planprice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSubscriptionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField(db_index=True)),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('interval_change', 'Interval change'), ('cancellation', 'Cancellation')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=12)),
                ('preview_snapshot', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_changes_requested', to=settings.AUTH_USER_MODEL)),
                ('target_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_changes', to='control_plane.plancatalog')),
                ('target_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_changes', to='billing.planprice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_changes', to='billing.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='UsageAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_key', models.SlugField(max_length=100)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_usage_aggregates', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_aggregates', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_key', models.SlugField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=24)),
                ('unit', models.CharField(max_length=40)),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=160)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('correction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_usage_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=80)),
                ('key_hash', models.CharField(max_length=64)),
                ('result_type', models.CharField(blank=True, max_length=80)),
                ('result_id', models.CharField(blank=True, max_length=160)),
                ('response_safe', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_idempotency_records', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'operation', 'key_hash'), name='unique_billing_mutation_key')],
            },
        ),
        migrations.CreateModel(
            name='BillingNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('locale', models.CharField(max_length=2)),
                ('adapter', models.CharField(default='console', max_length=24)),
                ('delivery_status', models.CharField(default='development_console', max_length=24)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('safe_context', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_notifications', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_billing_notification')],
            },
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(fields=('plan', 'currency', 'billing_interval'), name='unique_plan_currency_interval'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='plan_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status', 'current_period_end'], name='billing_sub_organiz_2c7ef1_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due', 'grace', 'paused', 'manual'])), fields=('organization',), name='one_effective_subscription_per_org'),
        ),
        migrations.AddConstraint(
            model_name='scheduledsubscriptionchange',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('subscription',), name='one_scheduled_subscription_change'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_minor__gte', 0)), name='invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid_minor__gte', 0)), name='invoice_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usageaggregate',
            constraint=models.UniqueConstraint(fields=('organization', 'subscription', 'meter_key', 'period_start'), name='unique_billing_usage_aggregate'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['organization', 'meter_key', 'period_start'], name='billing_usa_organiz_17ea3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_billing_usage_event'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('correction', True), _connector='OR'), name='usage_nonnegative_or_correction'),
        ),
    ]
