# Generated by Django 5.2 on 2026-08-17 07:10

import django.db.models.deletion
import organizations.models
import uuid
from django.db import migrations, models


def backfill_organization_wallets(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    BillingAccount = apps.get_model('billing', 'BillingAccount')
    OrganizationWallet = apps.get_model('billing', 'OrganizationWallet')
    currencies = dict(BillingAccount.objects.values_list('organization_id', 'default_currency'))
    for organization_id in Organization.objects.values_list('id', flat=True).iterator():
        currency = str(currencies.get(organization_id) or 'UZS').upper()
        OrganizationWallet.objects.get_or_create(
            organization_id=organization_id,
            currency=currency,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('control_plane', '0002_version_plan_catalog'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], db_index=True, default='active', max_length=12)),
                ('available_balance_minor', models.BigIntegerField(default=0)),
                ('ledger_version', models.PositiveBigIntegerField(default=0)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization_id', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='PlatformCatalogState',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('applied_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_balance_minor', models.BigIntegerField()),
                ('cached_balance_minor', models.BigIntegerField()),
                ('difference_minor', models.BigIntegerField()),
                ('ledger_entries', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('mismatch', 'Mismatch'), ('failed', 'Failed')], db_index=True, max_length=12)),
                ('safe_report', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('transaction_type', models.CharField(choices=[('top_up', 'Top up'), ('subscription_payment', 'Subscription payment'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('refund', 'Refund'), ('migration_credit', 'Migration credit')], max_length=24)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=12)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('safe_metadata', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('balance_after_minor', models.BigIntegerField()),
                ('ledger_version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_source',
            field=models.CharField(choices=[('wallet', 'Organization wallet'), ('manual', 'Manual'), ('fake', 'Deterministic fake'), ('future_external', 'Future external provider')], db_index=True, default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='organizationwallet',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='walletreconciliationrun',
            name='performed_by_platform_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_reconciliations_performed', to='control_plane.platformstaffaccess'),
        ),
        migrations.AddField(
            model_name='walletreconciliationrun',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='billing.organizationwallet'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transaction', to='billing.paymentattempt'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='performed_by_platform_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions_performed', to='control_plane.platformstaffaccess'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reverses_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_transaction', to='billing.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.organizationwallet'),
        ),
        migrations.AddConstraint(
            model_name='organizationwallet',
            constraint=models.UniqueConstraint(fields=('organization', 'currency'), name='unique_organization_wallet_currency'),
        ),
        migrations.AddConstraint(
            model_name='organizationwallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance_minor__gte', 0)), name='wallet_balance_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['organization', 'created_at'], name='billing_wal_organiz_9993d1_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'ledger_version'], name='billing_wal_wallet__749fb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='unique_wallet_transaction_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), ('status', 'completed'), ('transaction_type', 'subscription_payment')), fields=('invoice',), name='one_completed_wallet_debit_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='wallet_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after_minor__gte', 0)), name='wallet_transaction_balance_nonnegative'),
        ),
        migrations.RunPython(backfill_organization_wallets, migrations.RunPython.noop),
    ]
