from django.urls import path

from control_plane.views import (
    AIUsageView,
    AuditListView,
    ControlsView,
    DataRequestActionView,
    DataRequestDownloadView,
    DataRequestListView,
    EntitlementView,
    IncidentDetailView,
    IncidentListView,
    InternalCSRFView,
    InternalLoginView,
    InternalLogoutView,
    InternalMeView,
    JobActionView,
    JobListView,
    MFASetupView,
    MFAVerifyView,
    OrganizationActionView,
    OrganizationDetailView,
    OrganizationListView,
    OverviewView,
    ProviderActionView,
    ProviderListView,
    SessionListView,
    SettingsView,
    StaffDetailView,
    StaffListView,
)


urlpatterns = [
    path("auth/csrf/", InternalCSRFView.as_view(), name="csrf"),
    path("auth/login/", InternalLoginView.as_view(), name="login"),
    path("auth/mfa/setup/", MFASetupView.as_view(), name="mfa-setup"),
    path("auth/mfa/verify/", MFAVerifyView.as_view(), name="mfa-verify"),
    path("auth/logout/", InternalLogoutView.as_view(), name="logout"),
    path("auth/sessions/", SessionListView.as_view(), name="sessions"),
    path("me/", InternalMeView.as_view(), name="me"),
    path("overview/", OverviewView.as_view(), name="overview"),
    path("organizations/", OrganizationListView.as_view(), name="organizations"),
    path("organizations/<uuid:organization_id>/", OrganizationDetailView.as_view(), name="organization-detail"),
    path("organizations/<uuid:organization_id>/<str:action>/", OrganizationActionView.as_view(), name="organization-action"),
    path("controls/", ControlsView.as_view(), name="controls"),
    path("providers/", ProviderListView.as_view(), name="providers"),
    path("providers/<str:provider_type>/", ProviderListView.as_view(), name="provider-detail"),
    path("provider-connections/<uuid:connection_id>/action/", ProviderActionView.as_view(), name="provider-action"),
    path("ai/usage/", AIUsageView.as_view(), name="ai-usage"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<uuid:job_id>/<str:action>/", JobActionView.as_view(), name="job-action"),
    path("incidents/", IncidentListView.as_view(), name="incidents"),
    path("incidents/<uuid:incident_id>/", IncidentDetailView.as_view(), name="incident-detail"),
    path("data-requests/", DataRequestListView.as_view(), name="data-requests"),
    path("data-requests/<uuid:request_id>/download/", DataRequestDownloadView.as_view(), name="data-request-download"),
    path("data-requests/<uuid:request_id>/<str:action>/", DataRequestActionView.as_view(), name="data-request-action"),
    path("entitlements/<uuid:organization_id>/", EntitlementView.as_view(), name="entitlement"),
    path("audit/", AuditListView.as_view(), name="audit"),
    path("platform-staff/", StaffListView.as_view(), name="platform-staff"),
    path("platform-staff/<uuid:access_id>/", StaffDetailView.as_view(), name="platform-staff-detail"),
    path("settings/", SettingsView.as_view(), name="settings"),
]
