"""
Email / Form intake service.

Key design decisions
────────────────────
• Contact is created from the BODY of the email (requester's own data), NOT from
  the envelope sender (from_email).  The from_email is the shared mailbox that
  Power Automate / Outlook relays mail from — it must never be treated as the lead.
• If the body contains no contact identifier (email / phone), we fall back to
  from_email only as a last resort so no interaction is ever lost.
• The JobRecord.summary field is set to a concise 3-4 word title (e.g. "Plumbing
  Leak") generated by get_short_summary(), which uses a configurable AI prompt
  stored in SystemPrompt(key='email_short_summary').  Staff can edit that prompt
  in Django Admin without touching code.
• All structured form fields present in the body (requester contact, site address,
  community, lot/phase, city/state, preferred callback, issue description, etc.)
  are mapped to the correct model fields.
"""

import logging
import re
from typing import Any, Dict, Optional

from django.db import IntegrityError, transaction

from intake.models import (
    ChannelChoice,
    Contact,
    ContactSource,
    Interaction,
    InteractionCategory,
    InteractionStatus,
    JobRecord,
    JobStatus,
    PoRecStatus,
)
from intake.services.classification import (
    CATEGORY_JOB_REQUEST_INTAKE,
    CATEGORY_REVIEW_REQUIRED,
    _detect_specific_activity,
    _detect_trade,
    classify_text,
    detect_priority,
    extract_fields_from_text,
    get_short_summary,
    is_vague_request,
    normalize_lot_phase,
)
from jobs.services.notifications import fire_new_job_notifications, record_incoming_message

logger = logging.getLogger(__name__)

_CATEGORY_MAP = {
    'immediate_resolution': InteractionCategory.IMMEDIATE_RESOLUTION,
    'job_request_intake': InteractionCategory.JOB_REQUEST_INTAKE,
    'review_required': InteractionCategory.REVIEW_REQUIRED,
    'escalation': InteractionCategory.ESCALATION,
}

# ── Body-parsing patterns ─────────────────────────────────────────────────────
# Each key maps to an ordered list of regex patterns tried top-to-bottom.
# The first group-1 capture that produces a non-empty value wins.
_LABEL_PATTERNS: Dict[str, list] = {
    # ── Requester contact info (parsed from body, NOT from envelope sender) ──
    'requester_name': [
        r'^(?:requester\s+)?name\s*[:\-]\s*(.+)$',
        r'^your\s+name\s*[:\-]\s*(.+)$',
        r'^full\s+name\s*[:\-]\s*(.+)$',
        r'^contact\s+name\s*[:\-]\s*(.+)$',
        r'^submitted\s+by\s*[:\-]\s*(.+)$',
        r'^requested\s+by\s*[:\-]\s*(.+)$',
        r'^request(?:ed|or)\s*[:\-]\s*(.+)$',
        r'^requester\s*[:\-]\s*(.+)$',
        r'^from\s*[:\-]\s*(.+)$',
        r'^first\s+(?:and\s+last\s+)?name\s*[:\-]\s*(.+)$',
        r'^client\s+name\s*[:\-]\s*(.+)$',
    ],
    'requester_email': [
        r'^(?:your\s+)?e-?mail\s*(?:address)?\s*[:\-]?\s+(.+)$',
        r'^contact\s+e-?mail\s*[:\-]?\s+(.+)$',
        r'^reply\s+to\s*[:\-]?\s+(.+)$',
        r'^email\s*[:\-]?\s+(\S+@\S+\.\S+.*)$',
    ],
    'requester_phone': [
        r'^(?:your\s+)?phone\s*(?:number|#)?\s*[:\-]?\s+(\+?[\d\s().\-]{7,})$',
        r'^contact\s+phone\s*[:\-]?\s+(\+?[\d\s().\-]{7,})$',
        r'^mobile\s*(?:number|#)?\s*[:\-]?\s+(\+?[\d\s().\-]{7,})$',
        r'^cell\s*(?:phone|number|#)?\s*[:\-]?\s+(\+?[\d\s().\-]{7,})$',
        r'^telephone\s*[:\-]?\s+(\+?[\d\s().\-]{7,})$',
        r'^tel\.?\s*[:\-]?\s+(\+?[\d\s().\-]{7,})$',
    ],
    'preferred_callback': [
        r'^preferred\s+(?:call(?:back)?|access)\s*(?:time|window)?\s*[:\-]\s*(.+)$',
        r'^best\s+time\s+to\s+(?:call|reach)\s*[:\-]\s*(.+)$',
        r'^call(?:back)?\s+(?:window|time|preference)\s*[:\-]\s*(.+)$',
        r'^access\s+(?:time|window)\s*[:\-]\s*(.+)$',
        r'^availability\s*[:\-]\s*(.+)$',
    ],

    # ── Job / site fields ─────────────────────────────────────────────────────
    'builder': [
        r'^builder(?:\s+name)?\s*[:\-]\s*(.+)$',
    ],
    'project': [
        r'^project(?:\s+name)?\s*[:\-]\s*(.+)$',
    ],
    'site': [
        r'^(?:property\s+)?address\s*[:\-]\s*(.+)$',
        r'^site\s*[:\-]\s*(.+)$',
        r'^street\s*(?:address)?\s*[:\-]\s*(.+)$',
    ],
    'community': [
        r'^community\s*[:\-]\s*(.+)$',
        r'^subdivision\s*[:\-]\s*(.+)$',
        r'^property\s*/\s*community\s*[:\-]\s*(.+)$',
        r'^property\s+name\s*[:\-]\s*(.+)$',
        r'^complex\s*[:\-]\s*(.+)$',
    ],
    'lot_phase': [
        r'^lot\s*/\s*phase\s*[:\-]\s*(.+)$',
        r'^lot\s*(?:number|#|no\.?)?\s*[:\-]\s*(.+)$',
        r'^unit\s*(?:number|#|no\.?)?\s*[:\-]\s*(.+)$',
        r'^apt\.?\s*(?:number|#|no\.?)?\s*[:\-]\s*(.+)$',
        r'^apartment\s*(?:number|#)?\s*[:\-]\s*(.+)$',
        r'^phase\s*[:\-]\s*(.+)$',
        r'^suite\s*[:\-]\s*(.+)$',
    ],
    'city_state': [
        r'^city\s*(?:/\s*state)?\s*[:\-]\s*(.+)$',
        r'^state\s*[:\-]\s*(.+)$',
        r'^city\s*[:\-]\s*(.+)$',
    ],
    'service_type': [
        r'^service\s*type\s*[:\-]\s*(.+)$',
        r'^type\s+of\s+(?:work|service)\s*[:\-]\s*(.+)$',
        r'^work\s+type\s*[:\-]\s*(.+)$',
        r'^trade\s*[:\-]\s*(.+)$',
        r'^maintenance\s+type\s*[:\-]\s*(.+)$',
    ],
    'scope': [
        r'^issue\s+description\s*[:\-]\s*(.+)$',
        r'^(?:maintenance\s+)?issue\s*[:\-]\s*(.+)$',
        r'^problem\s*(?:description)?\s*[:\-]\s*(.+)$',
        r'^scope(?:\s+of\s+work)?\s*[:\-]\s*(.+)$',
        r'^description(?:\s+of\s+(?:work|issue))?\s*[:\-]\s*(.+)$',
        r'^work\s+description\s*[:\-]\s*(.+)$',
        r'^details?\s*[:\-]\s*(.+)$',
        r'^request\s+details?\s*[:\-]\s*(.+)$',
        # Contact-form style bodies commonly label the free-text request
        # with one of these three words; treat them as `scope` too.
        r'^message\s*[:\-]\s*(.+)$',
        r'^request\s*[:\-]\s*(.+)$',
        r'^inquiry\s*[:\-]\s*(.+)$',
    ],
    'quantity': [
        r'^quantity\s*[:\-]\s*(.+)$',
        r'^qty\s*[:\-]\s*(.+)$',
        r'^count\s*[:\-]\s*(.+)$',
    ],
    'urgency': [
        r'^urgency\s*[:\-]\s*(.+)$',
        r'^deadline\s*[:\-]\s*(.+)$',
        r'^priority\s*[:\-]\s*(.+)$',
        r'^timeline\s*[:\-]\s*(.+)$',
        r'^needed\s+by\s*[:\-]\s*(.+)$',
    ],
    'division': [
        r'^division\s*[:\-]\s*(.+)$',
        r'^department\s*[:\-]\s*(.+)$',
        r'^region\s*[:\-]\s*(.+)$',
    ],
    # PO and REC get their own buckets so both numbers can be captured
    # independently when the form lists them on separate lines.  They are
    # re-combined into ``po_rec_note`` by the webhook handler.
    #
    # The capture is restricted to identifier-safe characters
    # ([A-Za-z0-9 . _ - / #]) so that when an upstream relay accidentally
    # appends JSON tail to the body — e.g.
    #   "REC number: REC-5612","from":"tester@..."
    # — we stop at the first quote/comma/brace instead of swallowing the
    # whole JSON suffix into the value (which then exceeds
    # JobRecord.po_rec_note's 500-char max_length and aborts the DB insert).
    'po_number': [
        r'^po\s+number\s*[:\-]\s*([A-Za-z0-9][A-Za-z0-9._\-/#]*)',
        r'^purchase\s+order(?:\s+(?:number|no\.?|#))?\s*[:\-]\s*([A-Za-z0-9][A-Za-z0-9._\-/#]*)',
        r'^p\.?\s?o\.?\s*(?:number|no\.?|#)?\s*[:\-]\s*([A-Za-z0-9][A-Za-z0-9._\-/#]*)',
    ],
    'rec_number': [
        r'^rec\s+number\s*[:\-]\s*([A-Za-z0-9][A-Za-z0-9._\-/#]*)',
        r'^rec\s*(?:no\.?|#)?\s*[:\-]\s*([A-Za-z0-9][A-Za-z0-9._\-/#]*)',
    ],
    'po_rec_note': [
        r'^po\s*/\s*rec\s*[:\-]\s*(.+)$',
    ],
    'notes': [
        r'^(?:additional\s+)?notes?\s*[:\-]\s*(.+)$',
        r'^comments?\s*[:\-]\s*(.+)$',
        r'^remarks?\s*[:\-]\s*(.+)$',
    ],
}

# Simple email validation (not RFC-complete, good enough for form parsing)
_EMAIL_RE = re.compile(r'^[^@\s]+@[^@\s]+\.[^@\s]+$')

# Loose email / phone scanners used as a last-resort body sweep when neither
# the regex parser nor the LLM surfaced a requester identifier — people
# routinely drop their contact details in prose ("reach me at maria@ ...").
_LOOSE_EMAIL_RE = re.compile(r'\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b')
_LOOSE_PHONE_RE = re.compile(
    r'(?:(?<!\d)\+?1[\s.\-])?\(?\d{3}\)?[\s.\-]?\d{3}[\s.\-]?\d{4}(?!\d)'
)


def _first_body_email(body: str, *, exclude: set[str] | None = None) -> str:
    """Return the first email address found in ``body`` that's not in ``exclude``."""
    if not body:
        return ''
    exclude = {(e or '').lower() for e in (exclude or set())}
    for m in _LOOSE_EMAIL_RE.finditer(body):
        candidate = m.group(0).strip().lower()
        if not candidate:
            continue
        # Skip obvious no-reply / mailbox relay addresses.
        local = candidate.split('@', 1)[0]
        if local in {'noreply', 'no-reply', 'donotreply', 'do-not-reply',
                     'mailer-daemon', 'postmaster', 'notifications'}:
            continue
        if candidate in exclude:
            continue
        return candidate
    return ''


def _first_body_phone(body: str) -> str:
    """Return the first North-American-looking phone number in ``body`` (or '')."""
    if not body:
        return ''
    m = _LOOSE_PHONE_RE.search(body)
    return m.group(0).strip() if m else ''


def _strip_html(html: str) -> str:
    text = re.sub(
        r'<(style|script)[^>]*>.*?</(style|script)>',
        '', html, flags=re.IGNORECASE | re.DOTALL,
    )
    text = re.sub(r'<(?:br|p|div|tr|li|h\d)[^>]*>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]+>', '', text)
    for entity, char in (
            ('&nbsp;', ' '), ('&amp;', '&'), ('&lt;', '<'),
            ('&gt;', '>'), ('&quot;', '"'), ('&#39;', "'"),
            ('&#13;', ''), ('&#10;', '\n'),
    ):
        text = text.replace(entity, char)
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


# Some upstream relays (Power Automate, certain Outlook → JSON connectors,
# webhook bridges that JSON-encode the body twice) deliver the email body with
# *literal* backslash-r / backslash-n sequences instead of real newlines —
# i.e. the four characters "\", "r", "\", "n" appear inline rather than CR/LF.
# `str.splitlines()` does not split on those, so the line-oriented parser
# grabs the entire rest of the body into the first matched field
# ("Lot / phase: Lots 14 through 22\r\nAddress: ...\r\nCity / state: ...").
# Normalize them back to real newlines before any other processing.
_LITERAL_NEWLINE_RE = re.compile(r'\\r\\n|\\n|\\r')


def _normalize_literal_newlines(text: str) -> str:
    if not text or '\\' not in text:
        return text
    return _LITERAL_NEWLINE_RE.sub('\n', text)


# JSON-envelope leak detector.  Matches the canonical key separator
# `","keyname":` that JSON encoders produce between fields.  Each `"` /
# `,` may be preceded by an optional backslash so both the decoded form
# (Power Automate / Outlook → webhook delivers the body already
# JSON-decoded) and the doubly-encoded form (`\",\"keyname\":`) are
# caught by the same regex.  Used per-line by the body parser below to
# chop garbage that some flows leak into the email body field.
_JSON_TAIL_LEAK_RE = re.compile(r'\\?"\\?,\\?"\\?[A-Za-z_]\w*\\?":')


# Bullet / list prefixes we silently strip at the start of each line
# (•, ·, ▪, ●, ○, ◦, ·, →, plain dash/asterisk, and common numeric list markers).
_BULLET_PREFIX_RE = re.compile(
    r'^[\s\u00a0]*'                              # leading whitespace / NBSP
    r'(?:[\u2022\u2023\u2043\u25aa\u25cf\u25cb\u25e6\u00b7\*\-\u2192]|'  # glyph bullets
    r'\d{1,2}[.)])'                             # "1." / "1)" style numbering
    r'[\s\u00a0]+'
)


# ── Single-line labelled form pre-splitter ────────────────────────────────────
# Some contact-form relays (and mobile mail clients that strip newlines) flatten
# a multi-field form submission onto a single line:
#
#   "Name: Mike Torres Phone: 412-555-0193 Email: mike@... Message: I need …"
#
# The line-oriented parser below only matches labels at the start of a line, so
# on flattened input it would greedily capture the whole rest of the line into
# the first matched field (usually `requester_name`) and miss everything else.
#
# To fix that without rewriting the parser, we insert a newline in front of
# every KNOWN label that appears mid-line.  The behaviour is conservative:
#
#   • only fires when the input has no newlines (already multi-line → no-op);
#   • only fires when ≥ 2 distinct known labels appear;
#   • only matches labels that are preceded by whitespace or punctuation
#     and followed by ":" or "-", so a casual sentence like "Call me on
#     my phone today" is untouched (no colon after "phone").
#
# The list mirrors the labels in _LABEL_PATTERNS — if you add a new label
# there, add the short form here too.
_INLINE_LABEL_TOKENS = (
    'requester name', 'your name', 'full name', 'contact name',
    'first and last name', 'first name', 'client name', 'submitted by',
    'requested by', 'requestor', 'requester', 'name',
    'your email', 'contact email', 'email address', 'reply to',
    'e-mail', 'email',
    'your phone', 'contact phone', 'mobile number', 'mobile',
    'cell phone', 'cell', 'telephone', 'tel', 'phone',
    'builder name', 'builder', 'project name', 'project',
    'property address', 'street address', 'address', 'site', 'street',
    'property / community', 'property name',
    'subdivision', 'complex', 'community',
    'lot / phase', 'lot/phase', 'lot number', 'lot no', 'lot #', 'lot',
    'unit number', 'unit no', 'unit #', 'unit',
    'apt', 'apartment', 'phase', 'suite',
    'city / state', 'city/state', 'city', 'state',
    'service type', 'type of work', 'type of service', 'work type',
    'maintenance type', 'trade', 'service',
    'issue description', 'maintenance issue', 'problem description',
    'work description', 'request details', 'request detail',
    'issue', 'problem', 'scope of work', 'scope', 'description',
    'details', 'detail', 'message', 'inquiry',
    'quantity', 'qty', 'count',
    'urgency', 'deadline', 'priority', 'timeline', 'needed by',
    'division', 'department', 'region',
    'po / rec', 'purchase order', 'po number', 'rec number', 'po', 'rec',
    'additional notes', 'notes', 'note', 'comments', 'comment',
    'remarks', 'remark',
    'preferred callback', 'preferred access', 'preferred call',
    'best time to call', 'best time to reach',
    'callback window', 'callback time', 'callback preference',
    'access time', 'access window', 'availability',
    'request',
)

# One pre-compiled regex used by both `_explode_single_line_labels` and tests.
# Longest labels are ordered first so e.g. "property address" wins over plain
# "address".  Escaped, joined with `|`, wrapped as a named capture group.
#
# After the colon/dash we accept either whitespace (`\s`) OR end-of-string
# (`$`).  The end-of-string branch is what handles Outlook-wrapped bodies
# where a label sits at the end of one line and its value begins on the
# next — e.g.
#     "Lot / phase: Lots 14-22, City / state:\nPittsburgh, PA"
# Without the `$` branch the regex couldn't see "City / state:" as a label
# (no whitespace after the colon on that line), so the line-based parser
# greedily merged "City / state:" into the preceding field's value.
_INLINE_LABEL_RE = re.compile(
    r'(?:(?<=^)|(?<=[\s.,;()]))'
    r'(?P<label>(?:' + '|'.join(
        re.escape(t) for t in
        sorted(set(_INLINE_LABEL_TOKENS), key=len, reverse=True)
    ) + r'))'
    r'\s*[:\-](?=\s|$)',
    re.IGNORECASE,
)


def _explode_line_labels(line: str) -> list[str]:
    """Split a single physical line into one chunk per labelled field.

    Returns a list of substrings, each starting at a known label token.
    Returns ``[line]`` (1-element list) when the line contains fewer than
    two labels, so callers can treat the result uniformly.

    Example
    ───────
        "Name: Mike Phone: 412-... Email: mike@..."
      → ["Name: Mike", "Phone: 412-...", "Email: mike@..."]
    """
    matches = list(_INLINE_LABEL_RE.finditer(line))
    if len(matches) < 2:
        return [line]

    pieces: list[str] = []
    first_start = matches[0].start('label')
    if first_start > 0:
        head = line[:first_start].rstrip()
        if head:
            pieces.append(head)
    for i, m in enumerate(matches):
        start = m.start('label')
        end = matches[i + 1].start('label') if i + 1 < len(matches) else len(line)
        chunk = line[start:end].rstrip()
        if chunk:
            pieces.append(chunk)
    return pieces if len(pieces) >= 2 else [line]


def _explode_single_line_labels(text: str) -> str:
    """Per-line label exploder.

    Earlier the function only fired when the *entire* message was a single
    physical line (no \\n anywhere).  That left a bug class wide open: when
    Power Automate / Outlook adds even a single stray newline (header,
    trailing blank line, embedded signature) but the actual form body still
    sits on one long line, the explode was skipped entirely and the
    line-oriented parser captured everything into the first matched label
    (typical victim: ``requester_name`` swallows the whole flat string).

    Applying the explode per-line fixes that case while remaining a no-op
    for already-properly-formatted multi-line bodies.
    """
    if not text:
        return text

    out_lines: list[str] = []
    for line in text.splitlines():
        out_lines.extend(_explode_line_labels(line))
    return '\n'.join(out_lines)


def _parse_body_fields(body: str) -> Dict[str, str]:
    if not body:
        return {}

    text = _strip_html(body) if re.search(r'<[a-zA-Z]', body) else body
    # Some relays deliver bodies with literal "\r\n" text instead of real
    # newlines — convert them so splitlines() works correctly below.
    text = _normalize_literal_newlines(text)
    # Handle flattened single-line forms before the line-oriented parser runs.
    text = _explode_single_line_labels(text)

    extracted: Dict[str, str] = {}

    for line in text.splitlines():
        # Strip leading bullet / list markers so that "• Requester Name: …"
        # matches the same regexes as "Requester Name: …".
        line = _BULLET_PREFIX_RE.sub('', line).strip()
        # Truncate at the first JSON-envelope leak.  Power Automate /
        # Outlook → JSON connectors sometimes leak the envelope object
        # into a single line of the body, leaving a tail like:
        #   Service Type: Site Cleanup","importance":"normal","conversationId":"…
        # The literal sequence `","<json-key>":` (and its backslash-
        # escaped twin) never appears in a real email body — anything
        # from there onwards is garbage.  We cut per-line (NOT body-wide)
        # so a JSON leak on one field doesn't wipe out subsequent
        # legitimate fields that come after on later lines.
        m = _JSON_TAIL_LEAK_RE.search(line)
        if m:
            line = line[:m.start()].rstrip(' \t\r\n",')
        # Strip a trailing field-separator comma/semicolon left behind by the
        # single-line exploder so per-field regexes whose value char-classes
        # don't include "," (e.g. phone, email) still match.  We never strip
        # commas mid-string, so "Pittsburgh, PA" is unaffected.
        line = re.sub(r'[\s,;]+$', '', line)
        if not line:
            continue

        for field_name, patterns in _LABEL_PATTERNS.items():
            if field_name in extracted:
                continue
            for pattern in patterns:
                m = re.match(pattern, line, re.IGNORECASE)
                if m:
                    # Strip surrounding whitespace/quotes AND a single trailing
                    # comma/semicolon so flat comma-separated forms
                    # ("Community: Ridgeview Estates, Lot / phase: ...") don't
                    # leave a stray "," at the end of every value.  We don't
                    # strip commas anywhere else — "Pittsburgh, PA" must keep
                    # the comma between city and state.
                    value = m.group(1).strip(' \t\r\n"\'')
                    value = re.sub(r'[\s,;]+$', '', value)
                    if value:
                        extracted[field_name] = value
                    break

    # ── Natural-language fallback on the whole body ──────────────────────────
    # These heuristics pick up fields that customers mention in prose without
    # explicit labels — e.g. "in lot #42 of the ABC Homes development".
    # We only fill fields that weren't already matched by labelled regexes.
    for field_name, value in _extract_freeform_fields(text).items():
        if field_name not in extracted and value:
            extracted[field_name] = value

    return extracted


# ── Natural-language field extraction (no labels required) ───────────────────
# These patterns scan the full body (not line-by-line) to catch field values
# that customers mention in prose, e.g.:
#
#   "I need street cleaning in lot #42 of the ABC Homes development this week."
#
# We keep them *conservative*: each pattern only fires when it sees a clear
# contextual anchor (a known "company-suffix" word such as Homes / Builders /
# Development / Community, or the word "Lot" / "Unit" before a number).

# Suffix words that are part of a *company* name ("ABC Homes" — "Homes" stays
# in the builder field).
_COMPANY_SUFFIX = (
    r'(?:homes|builders?|construction|group|realty|properties|'
    r'residences|llc|inc|incorporated|corp(?:oration)?|co\.?)'
)

# Suffix words that mark a *location* type ("ABC Homes development" —
# "development" is NOT part of the builder name, but the whole phrase becomes
# the community value).
_LOCATION_SUFFIX = (
    r'(?:developments?|subdivisions?|communit(?:y|ies)|estates?|'
    r'villages?|ranch|farms?|phase)'
)

# Up to 4 capitalised tokens — "ABC", "Beacon Hill", "The Preserve at Elmwood".
_CAP_RUN = r"[A-Z][A-Za-z&'\-]+(?:\s+[A-Z][A-Za-z&'\-]+){0,3}"

_FREEFORM_PATTERNS = {
    # "in lot #42", "lot 14B", "Unit 7", "apartment #3" → lot_phase="Lot 42"
    'lot_phase': [
        (re.compile(
            r'\blot\s*(?:number\s*|no\.?\s*|#\s*)?(\d+[A-Za-z]?)\b',
            re.IGNORECASE,
         ), lambda m: f'Lot {m.group(1).upper()}'),
        (re.compile(
            r'\bunit\s*(?:number\s*|no\.?\s*|#\s*)?(\d+[A-Za-z]?)\b',
            re.IGNORECASE,
         ), lambda m: f'Unit {m.group(1).upper()}'),
        (re.compile(
            r'\b(?:apt\.?|apartment)\s*(?:number\s*|no\.?\s*|#\s*)?(\d+[A-Za-z]?)\b',
            re.IGNORECASE,
         ), lambda m: f'Apt {m.group(1).upper()}'),
        (re.compile(
            r'\bphase\s*(?:number\s*|no\.?\s*|#\s*)?(\d+[A-Za-z]?)\b',
            re.IGNORECASE,
         ), lambda m: f'Phase {m.group(1).upper()}'),
    ],

    # Two shapes for the builder:
    #  A) Ends in a *company suffix*  → keep the suffix inside the name
    #     "in ABC Homes"         → builder="ABC Homes"
    #     "from Lennar Builders" → builder="Lennar Builders"
    #  B) Ends in a *location suffix* → strip the suffix from the name
    #     "of the ABC Homes development" → builder="ABC Homes"
    #     "at Beacon Hill community"     → builder="Beacon Hill"
    'builder': [
        (re.compile(
            r'\b(?:of|at|in|by|from|for)\s+(?:the\s+)?'
            r'(?P<name>' + _CAP_RUN + r')\s+'
            r'(?P<suffix>' + _COMPANY_SUFFIX + r')\b',
            re.IGNORECASE,
         ), lambda m: f"{m.group('name').strip()} {m.group('suffix').strip().title()}"),
        (re.compile(
            r'\b(?:of|at|in|by|from|for)\s+(?:the\s+)?'
            r'(?P<name>' + _CAP_RUN + r')\s+' + _LOCATION_SUFFIX + r'\b',
            re.IGNORECASE,
         ), lambda m: m.group('name').strip()),
    ],

    # Community is only set for the location-suffix shape — "ABC Homes development"
    # becomes community="ABC Homes Development".
    'community': [
        (re.compile(
            r'\b(?:of|at|in|by)\s+(?:the\s+)?'
            r'(?P<name>' + _CAP_RUN + r')\s+'
            r'(?P<suffix>' + _LOCATION_SUFFIX + r')\b',
            re.IGNORECASE,
         ), lambda m: f"{m.group('name').strip()} {m.group('suffix').strip().title()}"),
    ],
}


def _extract_freeform_fields(text: str) -> Dict[str, str]:
    """Return a dict of field → value extracted from unlabeled prose.

    Empty if nothing matches.  Caller merges these as a *fallback* — labelled
    regex hits in the body still win.
    """
    if not text:
        return {}
    # Flatten newlines so patterns can span line breaks ("of the\nABC Homes").
    flat = re.sub(r'\s+', ' ', text)
    found: Dict[str, str] = {}
    for field_name, specs in _FREEFORM_PATTERNS.items():
        for pattern, builder in specs:
            m = pattern.search(flat)
            if not m:
                continue
            try:
                value = builder(m).strip(' \t\r\n"\',.;:')
            except Exception:
                continue
            if value and field_name not in found:
                found[field_name] = value
                break
    return found


def _normalize_email(raw: str) -> str:
    return raw.lower().strip() if raw else ''


# ── Inline PO / REC number recovery ───────────────────────────────────────────
# Matches phrasings like:
#   "PO is PO-2024-0871"
#   "po number PO-2024-0871"
#   "P.O.: PO-2024-0871"
#   "REC number REC-8845"
#
# We capture a contiguous token that includes at least one digit so we don't
# accidentally pick up the bare words "po" / "rec" inside normal prose.
# Direct-token patterns — match the canonical "PO-1234" / "REC-5612" shape
# anywhere in the body.  Preferred because it preserves the "PO-" / "REC-"
# prefix so the UI can display the identifier exactly as the customer typed
# it ("PO-2024-5580").
_DIRECT_PO_TOKEN_RE = re.compile(
    r'\b(PO[\-_\s]*\d[A-Za-z0-9_\-./#]{2,20})', re.IGNORECASE,
)
_DIRECT_REC_TOKEN_RE = re.compile(
    r'\b(REC[\-_\s]*\d[A-Za-z0-9_\-./#]{2,20})', re.IGNORECASE,
)

# Label-based fallback — for cases where the customer writes "PO is 2024-5580"
# without repeating the "PO-" prefix on the number itself.  We deliberately
# *don't* let the trailing number start with a bare "PO"/"REC" here because
# the direct-token pattern above already covers that case.
_INLINE_PO_RE = re.compile(
    r'\b(?:p\.?\s*o\.?(?:\s*number|\s*no\.?|\s*#)?|'
    r'po\s*(?:number|no\.?|#)?|purchase\s+order(?:\s+(?:number|no\.?|#))?)'
    r'\s*(?:is|:|-|=|#|for\s+this\s+is|for\s+this|number\s+is)?\s*'
    r'(?P<num>[A-Za-z][A-Za-z0-9_\-./]*\d[A-Za-z0-9_\-./]*|\d[A-Za-z0-9_\-./]*)',
    re.IGNORECASE,
)
_INLINE_REC_RE = re.compile(
    r'\brec(?:eiving)?(?:\s*(?:number|no\.?|#))?'
    r'\s*(?:is|:|-|=|#|for\s+this\s+is|for\s+this|number\s+is)?\s*'
    r'(?P<num>[A-Za-z][A-Za-z0-9_\-./]*\d[A-Za-z0-9_\-./]*|\d[A-Za-z0-9_\-./]*)',
    re.IGNORECASE,
)


def extract_inline_po_rec(body: str, *, kind: str) -> str:
    """Return a PO/REC identifier mentioned anywhere in ``body`` (or '').

    Preference order:
      1. Direct-token match (``PO-2024-5580`` / ``REC-5612``) — keeps the
         prefix exactly as the customer typed it.
      2. Label-based match (``PO is 5580``) — used only when no direct token
         is present; the captured number is returned verbatim, which the
         caller may optionally prefix.
    """
    if not body:
        return ''

    direct_re = _DIRECT_PO_TOKEN_RE if kind == 'po' else _DIRECT_REC_TOKEN_RE
    for m in direct_re.finditer(body):
        token = (m.group(1) or '').strip(' ,.;:')
        # Canonicalize separators: "PO 2024 5580" → "PO-2024-5580".
        token = re.sub(r'[\s_]+', '-', token)
        token = re.sub(r'-+', '-', token)
        if re.search(r'\d', token) and len(token) >= 5:
            return token

    label_re = _INLINE_PO_RE if kind == 'po' else _INLINE_REC_RE
    for m in label_re.finditer(body):
        candidate = (m.group('num') or '').strip(' ,.;:')
        if not candidate or len(candidate) < 3:
            continue
        if not re.search(r'\d', candidate):
            continue
        # If the candidate starts with a digit but we matched a PO/REC label,
        # prepend the canonical prefix so downstream display stays consistent.
        upper = candidate.upper()
        if kind == 'po' and not upper.startswith('PO'):
            candidate = f'PO-{candidate}'
        elif kind == 'rec' and not upper.startswith('REC'):
            candidate = f'REC-{candidate}'
        return candidate

    return ''


# ── Sufficiency check for job creation ───────────────────────────────────────
# A scope is considered "meaningful" only if it has real content beyond a
# greeting / throwaway phrase.  We accept ≥ 15 chars AND at least 3 words,
# which matches every real service request we've seen and rejects things like
# "Hello", "Please help", "Thanks".
_MIN_SCOPE_CHARS = 15
_MIN_SCOPE_WORDS = 3


def _is_meaningful_scope(scope: str) -> bool:
    if not scope:
        return False
    s = scope.strip()
    if len(s) < _MIN_SCOPE_CHARS:
        return False
    return len(s.split()) >= _MIN_SCOPE_WORDS


def _has_sufficient_job_info(
    *,
    service_type: str,
    scope: str,
    builder: str,
    project: str,
    site: str,
    community: str,
    lot_phase: str,
    body: str,
    has_structured_requester: bool = False,
) -> bool:
    """
    Decide whether we have enough data to create a JobRecord.

    Minimum bar (either path qualifies):

      Path A — strong trade signal:
        • A clearly identified *what* — explicit service_type OR a specific
          activity / trade keyword recognizable in the body, AND
        • A *where* signal — builder / project / site / community / lot_phase —
          OR a non-trivial scope that the assignee can actually work with.

      Path B — structured contact-form submission (safety net):
        • The requester is clearly identified (≥ 2 of name / email / phone
          came through the parser), AND
        • The scope is non-trivial AND not a vague placeholder phrase.

      Path B exists because customer-facing request forms legitimately use
      trades our keyword map doesn't yet know (e.g. "erosion control",
      "silt fence installation").  When the request is clearly structured
      AND has real content, dropping it into the Needs Review queue is
      worse than creating a job card with an empty service_type that
      a dispatcher can label after the fact.

    Vague-request gate (overrides both paths):
      If the *only* content we have to work with is a placeholder phrase
      like "Something is going on" — i.e. no service_type, no trade
      keyword, no quantity / location specifics — we refuse to create a
      job no matter how the classifier voted.  This matches QA
      requirement that drops "Something is going on…" into Needs Review
      rather than fabricating a "General Maintenance Issue" job card.
    """
    body_lower = (body or '').lower()

    has_what = bool(
        service_type
        or _detect_specific_activity(body_lower)
        or _detect_trade(body_lower)
    )
    has_where = bool(builder or project or site or community or lot_phase)
    has_scope = _is_meaningful_scope(scope)

    # Vague-only message check — fires only when we have no concrete *what*
    # signal at all.  When a trade is present ("Erosion control help us"),
    # the message is actionable and should NOT be blocked here.
    if not has_what and not has_where and is_vague_request(scope or body):
        return False

    if has_what and (has_where or has_scope):
        return True

    # Path B — structured form with a meaningful, non-vague message is
    # enough to justify auto-creation even without a known trade keyword.
    if has_structured_requester and has_scope and not is_vague_request(scope):
        return True

    return False


# Stricter scope thresholds for the "ready to schedule" gate.  ~30 chars and
# 5+ words filters out shallow placeholders like "Need help with erosion"
# while still accepting any real description of work.  Tuned against the QA
# test corpus.
_COMPLETE_SCOPE_CHARS = 30
_COMPLETE_SCOPE_WORDS = 5


def _has_complete_job_info(
    *,
    service_type: str,
    scope: str,
    community: str,
    lot_phase: str,
    site: str,
) -> bool:
    """Stricter bar than ``_has_sufficient_job_info`` — used to decide whether
    a freshly-created job goes straight to "Ready to schedule" status or
    starts in "Needs review" pending dispatcher confirmation.

    A job is "complete" when the dispatcher has, at a glance, every field
    they need to assign a crew without re-contacting the customer:
      • a concrete service_type (not inferred trade keyword), AND
      • a substantive scope (≥ 30 chars and ≥ 5 words — enough room for
        what / how-much / by-when), AND
      • at least ONE structured location field (community / lot / site).

    This is intentionally conservative: borderline jobs default to
    Needs Review so a human eyeball confirms the routing.
    """
    if not service_type or not service_type.strip():
        return False
    if not (community or lot_phase or site):
        return False
    s = (scope or '').strip()
    if len(s) < _COMPLETE_SCOPE_CHARS:
        return False
    if len(s.split()) < _COMPLETE_SCOPE_WORDS:
        return False
    return True


def build_field_request_title(
    *,
    service_type: str,
    community: str,
    lot_phase: str,
    site: str,
    fallback_summary: str,
) -> str:
    """Construct the structured Field Request title required by QA:

        "[Service] — [Community] (Lot)"

    Examples
    ────────
        ("Street Sweeping", "Sunset Ridge",     "Lot 42",       "")  → "Street Sweeping — Sunset Ridge (Lot 42)"
        ("Erosion Control", "Ridgeview Estates", "Lots 14–22",  "")  → "Erosion Control — Ridgeview Estates (Lots 14–22)"
        ("Drainage Repair", "Maple Ridge",      "",             "")  → "Drainage Repair — Maple Ridge"
        ("Site Cleanup",    "",                  "",             "")  → "Site Cleanup"     (LLM fallback only when no service)
        ("",                "",                  "",             "Plumbing leak summary")
                                                                     → "Plumbing leak summary"  (preserve LLM 3-word fallback)

    Component selection rules:
      • Service prefix wins over LLM summary when present, because QA needs
        the service_type front-and-center for triage.
      • Location prefers community; falls back to site address only when
        community is empty (it's still better than no location).
      • Lot suffix uses lot_phase verbatim, already normalised by
        ``normalize_lot_phase`` upstream.
    """
    service = (service_type or '').strip()
    location = (community or '').strip() or (site or '').strip()
    lot = (lot_phase or '').strip()

    if not service:
        # No service type — defer to whatever LLM summary we already have.
        return fallback_summary or ''

    parts = [service]
    if location:
        parts.append('—')
        parts.append(location)
    if lot:
        parts.append(f'({lot})')

    return ' '.join(parts).strip()


def process_email_webhook(payload: Dict[str, Any], *, organization, channel_connection) -> Interaction:
    """
    Process an inbound email / form webhook event.

    Contact lookup order
    ─────────────────────
    1. requester_email parsed from the email body  ← primary
    2. requester_phone parsed from the email body   ← if no email in body
    3. from_email (the envelope sender / shared mailbox)  ← fallback only

    This ensures that leads submitting forms are tracked by their own
    contact info, not by the shared operations mailbox.
    """
    from_email = _normalize_email(payload.get('from_email') or '')
    from_name = (payload.get('from_name') or '').strip()
    subject = (payload.get('subject') or '').strip()
    body = (payload.get('body') or '').strip()
    message_id = (payload.get('message_id') or '').strip()

    # ── Explicit structured fields passed directly in the webhook payload ─────
    explicit: Dict[str, str] = {
        'builder':        (payload.get('builder') or '').strip(),
        'project':        (payload.get('project') or '').strip(),
        'site':           (payload.get('site') or '').strip(),
        'community':      (payload.get('community') or '').strip(),
        'service_type':   (payload.get('service_type') or '').strip(),
        'scope':          (payload.get('scope') or '').strip(),
        'quantity':       (payload.get('quantity') or '').strip(),
        'urgency':        (payload.get('urgency') or '').strip(),
        'notes':          (payload.get('notes') or '').strip(),
        'division':       (payload.get('division') or '').strip(),
        'po_rec_note':    (payload.get('po_rec_note') or '').strip(),
        'po_number':      (payload.get('po_number') or '').strip(),
        'rec_number':     (payload.get('rec_number') or '').strip(),
        # Contact fields may also be passed explicitly by an advanced relay
        'requester_name':  (payload.get('requester_name') or '').strip(),
        'requester_email': _normalize_email(payload.get('requester_email') or ''),
        'requester_phone': (payload.get('requester_phone') or '').strip(),
        'preferred_callback': (payload.get('preferred_callback') or '').strip(),
        'lot_phase':      (payload.get('lot_phase') or '').strip(),
        'city_state':     (payload.get('city_state') or '').strip(),
    }

    # ── Parse body for structured fields ─────────────────────────────────────
    body_parsed = _parse_body_fields(body)
    if body_parsed:
        logger.info(
            'Email body parser extracted %d field(s): %s',
            len(body_parsed), sorted(body_parsed.keys()),
        )

    # ── LLM fallback for unstructured / natural-language emails ──────────────
    # Regex patterns catch ~90% of well-formatted emails but miss synonyms
    # ("Site address" vs "Property address"), labels glued to values without a
    # space after the colon, labels split over two lines, etc.  Running the
    # LLM on every inbound email and merging it as a *fallback* (regex still
    # wins) reliably fills these gaps — at the cost of a single cheap API call.
    llm_parsed: Dict[str, str] = {}
    if body or subject:
        try:
            llm_text = (subject + '\n\n' + body).strip() if subject else body
            llm_parsed = extract_fields_from_text(llm_text) or {}
            if llm_parsed:
                logger.info(
                    'Email LLM extractor recovered %d field(s): %s',
                    len(llm_parsed), sorted(llm_parsed.keys()),
                )
        except Exception as exc:
            logger.warning('Email LLM extractor failed: %s', type(exc).__name__)

    def _merge(field: str) -> str:
        """Explicit payload > regex-parsed body > LLM-extracted."""
        return (
            explicit.get(field)
            or body_parsed.get(field, '')
            or llm_parsed.get(field, '')
        )

    # Per-field length caps that mirror the JobRecord / Contact / Interaction
    # max_length attributes.  Truncating defensively here means a malformed
    # body (e.g. JSON tail accidentally appended by an upstream relay) can
    # never trigger a DB DataError that would abort the whole webhook with a
    # generic "Processing error".
    _MAX = {
        'builder':            255,
        'project':            255,
        'site':               255,
        'community':          255,
        'service_type':       255,
        'quantity':           100,
        'urgency':            500,
        'division':           255,
        'po_number':           80,
        'rec_number':          80,
        'po_rec_note':        500,
        'lot_phase':          255,
        'city_state':         255,
        'requester_name':     255,
        'requester_email':    254,
        'requester_phone':     30,
        'preferred_callback': 500,
    }

    def _safe(field: str) -> str:
        return _merge(field)[: _MAX.get(field, 1000)]

    # Job / site fields
    builder      = _safe('builder')
    project      = _safe('project')
    site         = _safe('site')
    community    = _safe('community')
    service_type = _safe('service_type')
    scope        = _merge('scope')  # EncryptedTextField — no length limit
    quantity     = _safe('quantity')
    urgency      = _safe('urgency')
    notes        = _merge('notes')  # EncryptedTextField — no length limit
    division     = _safe('division')
    po_rec_note  = _safe('po_rec_note')
    po_number    = _safe('po_number')
    rec_number   = _safe('rec_number')
    lot_phase    = _safe('lot_phase')
    city_state   = _safe('city_state')

    # Fold city/state into ``site`` so the address is stored as one full string
    # ("1240 Ridgeview Drive, Pittsburgh, PA").  ``city_state`` is still mirrored
    # to Contact.metadata below so the serializer's contact_city_state field
    # keeps working unchanged.
    if site and city_state and city_state.lower() not in site.lower():
        site = f'{site}, {city_state}'[:_MAX['site']]

    # Canonicalise lot ranges so "Lots 14 through 22", "Lot 14-22", and
    # "Lots 14–22" all surface as the same value downstream.
    lot_phase    = normalize_lot_phase(lot_phase)

    # ── Freeform PO / REC recovery ─────────────────────────────────────────────
    # Many customers mention their PO / REC inside the scope sentence rather
    # than as a labelled field: "PO is PO-2024-0871. REC number REC-8845.".
    # If no explicit labelled value surfaced, scan the full body for common
    # PO-XXXX / REC-XXXX tokens.
    if not po_number:
        po_number = extract_inline_po_rec(body, kind='po') or po_number
    if not rec_number:
        rec_number = extract_inline_po_rec(body, kind='rec') or rec_number

    # ── Collapse PO / REC into the display field ──────────────────────────────
    # The JobRecord model stores a single ``po_rec_note`` string.  Preserve
    # any existing free-form value, but give PO / REC numbers a clean format
    # so the frontend can split them back out if ever needed.
    po_rec_parts = []
    if po_number:
        po_rec_parts.append(f'PO: {po_number}')
    if rec_number:
        po_rec_parts.append(f'REC: {rec_number}')
    if po_rec_parts:
        combined = ' | '.join(po_rec_parts)
        po_rec_note = combined if not po_rec_note else f'{combined} | {po_rec_note}'

    # Requester contact fields
    req_name     = _safe('requester_name')
    req_email    = _safe('requester_email')
    req_phone    = _safe('requester_phone')
    preferred_callback = _safe('preferred_callback')

    # Validate the body-extracted email looks like an actual email address
    if req_email and not _EMAIL_RE.match(req_email):
        logger.warning('Body-parsed requester_email looks invalid (%r), discarding', req_email[:60])
        req_email = ''

    # ── Last-resort body sweep ─────────────────────────────────────────────────
    # Prose-heavy requests ("you can reach me at maria@sunsetbuild.com or
    # 412-555-2200") often slip past both the labelled-regex parser and the LLM
    # fallback.  Scan the raw body for the first plausible email / phone that
    # isn't the envelope sender.
    if not req_email:
        scanned = _first_body_email(body, exclude={from_email})
        if scanned and _EMAIL_RE.match(scanned):
            req_email = scanned
    if not req_phone:
        scanned_phone = _first_body_phone(body)
        if scanned_phone:
            req_phone = scanned_phone

    # ── Contact resolution: body data first, sender as last resort ────────────
    # Prefer body-extracted email; fall back to phone; fall back to from_email.
    contact: Optional[Contact] = None
    contact_identifier_used = ''

    if req_email:
        contact_identifier_used = 'body_email'
        try:
            contact, created = Contact.objects.get_or_create(
                organization=organization,
                email=req_email,
                defaults={
                    'name': req_name or from_name,
                    'phone': req_phone,
                    'source': ContactSource.EMAIL,
                },
            )
        except IntegrityError:
            contact = Contact.objects.get(organization=organization, email=req_email)
            created = False

        # Update name / phone if we have better data now.  Also overwrite a
        # placeholder name that looks like an email address (happens when the
        # very first touchpoint was the envelope-sender fallback) — a real
        # body-parsed name ("Mike Torres") should win over "mike@acme.com".
        needs_save = []
        existing_name = (contact.name or '').strip()
        existing_looks_like_email = '@' in existing_name
        if req_name and (not existing_name or existing_looks_like_email):
            contact.name = req_name
            needs_save.append('name')
        if req_phone and not contact.phone:
            contact.phone = req_phone
            needs_save.append('phone')
        if needs_save:
            contact.save(update_fields=needs_save)

        if created:
            logger.info('New contact created from body email (masked)')

    elif req_phone:
        contact_identifier_used = 'body_phone'
        try:
            contact, created = Contact.objects.get_or_create(
                organization=organization,
                phone=req_phone,
                defaults={
                    'name': req_name or from_name,
                    'email': req_email or '',
                    'source': ContactSource.EMAIL,
                },
            )
        except IntegrityError:
            contact = Contact.objects.get(organization=organization, phone=req_phone)
            created = False

        needs_save = []
        if req_name and not contact.name:
            contact.name = req_name
            needs_save.append('name')
        if req_email and not contact.email:
            contact.email = req_email
            needs_save.append('email')
        if needs_save:
            contact.save(update_fields=needs_save)

        if created:
            logger.info('New contact created from body phone (masked)')

    elif from_email:
        contact_identifier_used = 'sender_email_fallback'
        logger.info(
            'No requester contact in body — using envelope sender as fallback '
            '(from_email masked)'
        )
        try:
            contact, created = Contact.objects.get_or_create(
                organization=organization,
                email=from_email,
                defaults={'name': from_name, 'source': ContactSource.EMAIL},
            )
        except IntegrityError:
            contact = Contact.objects.get(organization=organization, email=from_email)
            created = False

        if created:
            logger.info('New contact created from sender email (masked)')
        else:
            needs_save = []
            # Body-parsed name wins over envelope "from_name" (which is
            # usually the inbox display name, not the requester).
            if req_name and contact.name != req_name:
                contact.name = req_name
                needs_save.append('name')
            elif from_name and not contact.name:
                contact.name = from_name
                needs_save.append('name')
            if req_phone and not contact.phone:
                contact.phone = req_phone
                needs_save.append('phone')
            if needs_save:
                contact.save(update_fields=needs_save)

    # Store preferred_callback + city_state in Contact.metadata (no model change)
    if contact and (preferred_callback or city_state):
        meta = contact.metadata or {}
        changed = False
        if preferred_callback and not meta.get('preferred_callback'):
            meta['preferred_callback'] = preferred_callback
            changed = True
        if city_state and not meta.get('city_state'):
            meta['city_state'] = city_state
            changed = True
        if changed:
            contact.metadata = meta
            contact.save(update_fields=['metadata'])

    # ── Classification ────────────────────────────────────────────────────────
    combined = ' '.join(filter(None, [subject, body, service_type, scope, notes]))
    category_str, confidence, reason = classify_text(combined, organization=organization)

    # Presence of structured job fields is a strong signal → upgrade classification.
    # Count the fields across explicit / regex / LLM; require ≥ 2 strong signals.
    strong_fields = [builder, project, site, service_type, scope, community, lot_phase]
    filled = sum(1 for f in strong_fields if f)
    # "Structured requester" = the parser recovered ≥ 2 of the three primary
    # identifiers from the body.  Treated as a form submission.
    requester_signals = sum(1 for f in (req_name, req_email, req_phone) if f)
    has_structured_requester = requester_signals >= 2
    if filled >= 2:
        category_str = CATEGORY_JOB_REQUEST_INTAKE
        confidence = max(confidence, 0.80)
        reason = 'structured-job-fields'
    elif filled == 1 and (req_name or req_email or req_phone):
        # One job field + a clearly identified requester is still enough.
        category_str = CATEGORY_JOB_REQUEST_INTAKE
        confidence = max(confidence, 0.70)
        reason = 'single-field-plus-requester'
    elif has_structured_requester and _is_meaningful_scope(scope):
        # Structured contact-form submission with a real message — treat as
        # a job request even if no job-ish keywords were detected.
        category_str = CATEGORY_JOB_REQUEST_INTAKE
        confidence = max(confidence, 0.70)
        reason = 'structured-requester-plus-scope'

    # ── Sufficiency gate for job creation ────────────────────────────────────
    # Even when the classifier says "job_request_intake", we refuse to
    # fabricate a JobRecord out of thin air.  A real job card needs, at
    # minimum, a recognizable *what* (trade or activity) AND a *where* (any
    # location signal) OR a non-trivial scope — OR, as a safety net, a
    # structured contact-form submission with a real message body.
    if category_str == CATEGORY_JOB_REQUEST_INTAKE and not _has_sufficient_job_info(
        service_type=service_type, scope=scope,
        builder=builder, project=project, site=site,
        community=community, lot_phase=lot_phase,
        body=body,
        has_structured_requester=has_structured_requester,
    ):
        logger.info(
            'Email classified as job_request_intake but fails sufficiency '
            'gate — downgrading to review_required (filled=%d, service_type=%r, '
            'requester_signals=%d)',
            filled, bool(service_type), requester_signals,
        )
        category_str = CATEGORY_REVIEW_REQUIRED
        confidence = min(confidence, 0.45)
        reason = 'insufficient-job-info'

    interaction_category = _CATEGORY_MAP.get(category_str, InteractionCategory.REVIEW_REQUIRED)
    interaction_status = (
        InteractionStatus.REVIEW_REQUIRED
        if interaction_category == InteractionCategory.REVIEW_REQUIRED
        else InteractionStatus.NEW
    )

    # ── Build raw_content ─────────────────────────────────────────────────────
    raw_text = (
        f'Subject: {subject}\n'
        f'From: {from_name} <{from_email}> [envelope sender]\n'
        f'Requester: {req_name} <{req_email}> (body-parsed, identifier={contact_identifier_used})\n'
        f'\n{body}'
    )

    with transaction.atomic():
        interaction = Interaction.objects.create(
            organization=organization,
            channel_connection=channel_connection,
            channel=ChannelChoice.EMAIL,
            contact=contact,
            caller_email=req_email or from_email,
            caller_phone=req_phone,
            category=interaction_category,
            status=interaction_status,
            raw_content=raw_text,
            provider_id=message_id,
            provider_payload=payload,
            classification_confidence=confidence,
            classification_reason=reason,
        )

        job: Optional[JobRecord] = None
        if category_str == CATEGORY_JOB_REQUEST_INTAKE:
            # ── Job-card title ────────────────────────────────────────────────
            # QA requirement: every job card surfaces as
            #     "[Service] — [Community] (Lot)"
            # so the hotlist is scannable without opening details.  We still
            # call the LLM short-summary helper as a *fallback* — it kicks
            # in only when there's no service_type to anchor the title.
            llm_summary = get_short_summary(
                text=scope or notes or body[:600],
                service_type=service_type,
                organization=organization,
            )
            summary_text = build_field_request_title(
                service_type=service_type,
                community=community,
                lot_phase=lot_phase,
                site=site,
                fallback_summary=llm_summary,
            ) or llm_summary

            # Map lot_phase → project for the dispatcher's "Lot/phase" column.
            # community stays in its own field so the two never blend.
            effective_project = project or lot_phase

            # Infer priority from the full context (subject + body + scope +
            # explicit urgency label) — we never ask the customer directly
            # because self-reported urgency is unreliable.
            inferred_priority = detect_priority(
                text=' '.join(filter(None, [subject, body, scope, notes])),
                urgency_notes=urgency,
            )

            # Status routing — QA req: complete-data jobs skip "Needs review"
            # and land directly in "Ready to schedule" (PRIORITIZED).  Partial
            # jobs still go through PENDING_REVIEW so a human verifies routing
            # before a crew gets dispatched.
            initial_status = (
                JobStatus.PRIORITIZED
                if _has_complete_job_info(
                    service_type=service_type, scope=scope,
                    community=community, lot_phase=lot_phase, site=site,
                )
                else JobStatus.PENDING_REVIEW
            )

            job = JobRecord.objects.create(
                organization=organization,
                source_channel=ChannelChoice.EMAIL,
                contact=contact,
                source_interaction=interaction,
                service_type=service_type,
                builder=builder,
                project=effective_project,
                site=site,
                community=community,
                scope=scope,
                quantity=quantity,
                urgency_notes=urgency,
                priority=inferred_priority,
                division=division,
                po_rec_note=po_rec_note,
                po_required=bool(po_number),
                rec_required=bool(rec_number),
                po_status=PoRecStatus.RECEIVED if po_number else PoRecStatus.NOT_REQUIRED,
                rec_status=PoRecStatus.RECEIVED if rec_number else PoRecStatus.NOT_REQUIRED,
                summary=summary_text,
                status=initial_status,
            )
            interaction.related_job = job
            interaction.save(update_fields=['related_job'])
            fire_new_job_notifications(job)

            # Timeline entry with the actual email body so staff can see
            # what the customer wrote, not only a short summary.
            sender_label = req_name or req_email or from_name or from_email or 'Email'
            record_incoming_message(
                job, channel='email',
                body=(scope or notes or body),
                sender=sender_label,
            )

            logger.info(
                'Email job record created: job=%s interaction=%s '
                'builder=%r service_type=%r site=%r summary=%r',
                str(job.id)[:8], str(interaction.id)[:8],
                builder, service_type, site, summary_text,
            )

        logger.info(
            'Email interaction created: id=%s category=%s has_job=%s contact_via=%s',
            str(interaction.id)[:8], category_str,
            job is not None, contact_identifier_used,
        )

    return interaction
