# Generated by Django 5.2 on 2026-08-14 08:00

import core.utils.encryption
import django.db.models.deletion
import organizations.models
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_manual_entitlements(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    PlanCatalog = apps.get_model('control_plane', 'PlanCatalog')
    OrganizationEntitlement = apps.get_model('control_plane', 'OrganizationEntitlement')
    plan, _ = PlanCatalog.objects.get_or_create(
        key='manual',
        defaults={
            'display_name': 'Manual',
            'feature_flags': {
                'channels': True,
                'ai': True,
                'voice': True,
                'branches': True,
                'seats': True,
                'usage': True,
            },
            'default_limits': {'seats': 25, 'branches': 25},
            'internal_notes': 'Safe default for organizations created before billing exists.',
        },
    )
    existing = set(OrganizationEntitlement.objects.values_list('organization_id', flat=True))
    OrganizationEntitlement.objects.bulk_create([
        OrganizationEntitlement(organization_id=organization_id, plan=plan, status='manual')
        for organization_id in Organization.objects.values_list('id', flat=True)
        if organization_id not in existing
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('organizations', '0002_branch_working_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCatalog',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('feature_flags', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('default_limits', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('internal_notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed'), ('dead_letter', 'Dead letter'), ('cancelled', 'Cancelled'), ('acknowledged', 'Acknowledged')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('idempotency_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('idempotent', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_jobs', to='channels.channelconnection')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_jobs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStaffAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('platform_owner', 'Platform owner'), ('platform_admin', 'Platform administrator'), ('operations', 'Operations'), ('support', 'Support'), ('security_auditor', 'Security auditor')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='invited', max_length=16)),
                ('mfa_required', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_privileged_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_accesses', to='control_plane.platformstaffaccess')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('user_agent_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('ip_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='control_plane.platformstaffaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Authenticator', max_length=120)),
                ('secret_encrypted', core.utils.encryption.EncryptedTextField(editable=False)),
                ('recovery_code_hashes', models.JSONField(blank=True, default=list)),
                ('last_time_step', models.BigIntegerField(default=-1)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to='control_plane.platformstaffaccess')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('title', models.CharField(max_length=240)),
                ('safe_summary', models.TextField(max_length=4000)),
                ('affected_provider', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_organizations', models.ManyToManyField(blank=True, related_name='platform_incidents', to='organizations.organization')),
                ('linked_jobs', models.ManyToManyField(blank=True, related_name='incidents', to='control_plane.operationaljob')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='control_plane.platformstaffaccess')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to='control_plane.platformstaffaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformDataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('export', 'Export'), ('anonymize', 'Anonymize'), ('delete', 'Delete')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('identity_verification', 'Identity verification'), ('approved', 'Approved'), ('running', 'Running'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=28)),
                ('reason', models.CharField(max_length=1000)),
                ('scope', models.JSONField(default=dict, validators=[organizations.models.validate_json_object])),
                ('approval_required', models.PositiveSmallIntegerField(default=1)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('export_reference', models.CharField(blank=True, editable=False, max_length=160)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to='organizations.organization')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_data_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ManyToManyField(blank=True, related_name='data_requests_approved', to='control_plane.platformstaffaccess')),
                ('requested_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_requests_created', to='control_plane.platformstaffaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_role', models.CharField(blank=True, choices=[('platform_owner', 'Platform owner'), ('platform_admin', 'Platform administrator'), ('operations', 'Operations'), ('support', 'Support'), ('security_auditor', 'Security auditor')], max_length=24)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('target_type', models.CharField(db_index=True, max_length=80)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('reason', models.CharField(max_length=1000)),
                ('before_summary', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('after_summary', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('network_hash', models.CharField(blank=True, max_length=64)),
                ('mfa_fresh', models.BooleanField(default=False)),
                ('result', models.CharField(default='success', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_audit_events', to='organizations.organization')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='control_plane.platformstaffaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationOperationalState',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operational_state', serialize=False, to='organizations.organization')),
                ('marked_for_review', models.BooleanField(default=False)),
                ('new_logins_disabled', models.BooleanField(default=False)),
                ('provider_sends_disabled', models.BooleanField(default=False)),
                ('ai_disabled', models.BooleanField(default=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('lifecycle_reason', models.CharField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_states', to='control_plane.platformstaffaccess')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEntitlement',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='entitlement', serialize=False, to='organizations.organization')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace'), ('suspended', 'Suspended'), ('manual', 'Manual')], db_index=True, default='manual', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('feature_overrides', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('limit_overrides', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_entitlements', to='control_plane.plancatalog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements_updated', to='control_plane.platformstaffaccess')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('global_ai', 'Global AI'), ('global_ai_tool', 'Global AI tool'), ('global_provider', 'Global provider'), ('organization_ai', 'Organization AI'), ('organization_ai_tool', 'Organization AI tool'), ('organization_provider', 'Organization provider'), ('channel_connection', 'Channel connection'), ('voice_global', 'Global Voice calls'), ('external_autopilot', 'External autopilot')], db_index=True, max_length=32)),
                ('provider_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(max_length=1000)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('restored_reason', models.CharField(blank=True, max_length=1000)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_controls', to='channels.channelconnection')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_controls', to='organizations.organization')),
                ('activated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls_activated', to='control_plane.platformstaffaccess')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls_restored', to='control_plane.platformstaffaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSupportNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_notes', to='control_plane.platformstaffaccess')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_support_notes', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationaljob',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='control_pla_organiz_676714_idx'),
        ),
        migrations.AddIndex(
            model_name='platformstaffaccess',
            index=models.Index(fields=['status', 'role'], name='control_pla_status_62727c_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsession',
            index=models.Index(fields=['access', 'revoked_at', 'expires_at'], name='control_pla_access__66fd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='platformdatarequest',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='control_pla_organiz_76e227_idx'),
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['organization', '-created_at'], name='control_pla_organiz_f8e930_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcontrol',
            index=models.Index(fields=['active', 'kind', 'provider_type'], name='control_pla_active_e42606_idx'),
        ),
        migrations.RunPython(seed_manual_entitlements, migrations.RunPython.noop),
    ]
