# Generated by Django 5.2 on 2026-08-10 11:12

import crm.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant_context', '0001_initial'),
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0003_conversation_ai_state_and_more'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_for_approval', 'Waiting for approval'), ('completed', 'Completed'), ('handoff', 'Handoff'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], db_index=True, default='queued', max_length=30)),
                ('mode', models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot')], max_length=20)),
                ('provider', models.CharField(choices=[('fake', 'Deterministic fake'), ('openai', 'OpenAI Responses API')], max_length=20)),
                ('model', models.CharField(max_length=120, validators=[crm.models.validate_plain_text])),
                ('prompt_template_version', models.CharField(max_length=40)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('response_id', models.CharField(blank=True, max_length=120)),
                ('provider_request_id', models.CharField(blank=True, max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('tool_rounds', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.CharField(blank=True, choices=[('', 'Pending'), ('draft', 'Draft'), ('sent_test_reply', 'Sent internal test reply'), ('handoff', 'Handoff'), ('no_reply', 'No reply'), ('failed', 'Failed')], max_length=30)),
                ('response_language', models.CharField(blank=True, max_length=2)),
                ('error_category', models.CharField(blank=True, max_length=60)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('task_key', models.CharField(max_length=160, unique=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_context_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='assistant_context.assistantcontextrevision')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='crm.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('trigger_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triggered_ai_runs', to='crm.message')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80)),
                ('safe_summary', models.TextField(max_length=2000, validators=[crm.models.validate_plain_text])),
                ('requested_by', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('policy', 'Policy'), ('system', 'System')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_handoffs', to='organizations.organizationmembership')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_handoffs', to='crm.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to='ai_runtime.airun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=10000, validators=[crm.models.validate_plain_text])),
                ('language', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('edited_and_sent', 'Edited and sent'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=30)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts_approved', to='organizations.organizationmembership')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='crm.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts_rejected', to='organizations.organizationmembership')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='ai_runtime.airun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(editable=False, max_length=80)),
                ('provider_call_id', models.CharField(editable=False, max_length=160)),
                ('input_redacted', models.JSONField(default=dict, editable=False, validators=[crm.models.validate_safe_metadata])),
                ('output_redacted', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', max_length=30)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('error_category', models.CharField(blank=True, max_length=60)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tool_calls_approved', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai_runtime.airun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIToolPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('execution_mode', models.CharField(choices=[('automatic', 'Automatic'), ('require_approval', 'Require approval'), ('disabled', 'Disabled')], default='disabled', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tool_policies_updated', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ['tool_name'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
                ('date_bucket', models.DateField(db_index=True)),
                ('month_bucket', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_event', to='ai_runtime.airun')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000, validators=[crm.models.validate_plain_text])),
                ('is_ai_generated', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='crm.conversation')),
                ('end_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries_ended', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('start_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries_started', to='crm.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAIRuntimeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('default_mode', models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot')], default='off', max_length=20)),
                ('provider', models.CharField(choices=[('fake', 'Deterministic fake'), ('openai', 'OpenAI Responses API')], default='fake', max_length=20)),
                ('model', models.CharField(default='configured-model', max_length=120, validators=[crm.models.validate_plain_text])),
                ('max_output_tokens', models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(4000)])),
                ('max_tool_rounds', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(120)])),
                ('inbound_debounce_seconds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('daily_run_limit', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('monthly_input_token_limit', models.PositiveIntegerField(default=500000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000000)])),
                ('monthly_output_token_limit', models.PositiveIntegerField(default=100000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(50000000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_channel_connections', models.ManyToManyField(blank=True, related_name='ai_runtime_configs', to='channels.channelconnection')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runtime_config', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runtime_configs_updated', to='organizations.organizationmembership')),
            ],
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='ai_runtime__organiz_109983_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['organization', 'conversation', '-created_at'], name='ai_runtime__organiz_dae73f_idx'),
        ),
        migrations.AddConstraint(
            model_name='airun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'waiting_for_approval'])), fields=('conversation',), name='one_active_ai_run_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='aihandoff',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='ai_runtime__organiz_43e01b_idx'),
        ),
        migrations.AddConstraint(
            model_name='aitoolcall',
            constraint=models.UniqueConstraint(fields=('run', 'provider_call_id'), name='unique_provider_call_per_run'),
        ),
        migrations.AddConstraint(
            model_name='aitoolpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'tool_name'), name='unique_org_ai_tool_policy'),
        ),
        migrations.AddIndex(
            model_name='aiusageevent',
            index=models.Index(fields=['organization', 'date_bucket'], name='ai_runtime__organiz_f65a28_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusageevent',
            index=models.Index(fields=['organization', 'month_bucket'], name='ai_runtime__organiz_206c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['organization'], name='ai_runtime__organiz_81a450_idx'),
        ),
    ]
