# Generated by Django 5.1.4 on 2026-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_runtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='mode',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='airun',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', 'Pending'), ('draft', 'Draft'), ('sent_test_reply', 'Sent internal test reply'), ('sent_web_chat_reply', 'Sent Web Chat reply'), ('handoff', 'Handoff'), ('no_reply', 'No reply'), ('failed', 'Failed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationairuntimeconfig',
            name='default_mode',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot')], default='off', max_length=20),
        ),
    ]
