# Generated by Django 5.2 on 2026-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_runtime', '0003_alter_airun_mode_alter_airun_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='mode',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot'), ('autopilot_instagram', 'Instagram autopilot'), ('autopilot_telegram', 'Telegram autopilot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='airun',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', 'Pending'), ('draft', 'Draft'), ('sent_test_reply', 'Sent internal test reply'), ('sent_web_chat_reply', 'Sent Web Chat reply'), ('sent_instagram_reply', 'Sent Instagram reply'), ('sent_telegram_reply', 'Sent Telegram reply'), ('handoff', 'Handoff'), ('no_reply', 'No reply'), ('failed', 'Failed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationairuntimeconfig',
            name='default_mode',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot'), ('autopilot_instagram', 'Instagram autopilot'), ('autopilot_telegram', 'Telegram autopilot')], default='off', max_length=20),
        ),
    ]
