# Generated by Django 5.1.4 on 2026-08-10 13:40

import crm.models
import django.core.validators
import django.db.models.deletion
import uuid
import web_chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0004_alter_conversation_ai_state'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebChatInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(default=web_chat.models.generate_public_key, editable=False, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=20)),
                ('display_name', models.CharField(default='Website chat', max_length=160, validators=[crm.models.validate_plain_text])),
                ('assistant_label', models.CharField(default='Assistant', max_length=120, validators=[crm.models.validate_plain_text])),
                ('greeting', models.CharField(default='Hello! How can we help?', max_length=500, validators=[crm.models.validate_plain_text])),
                ('offline_message', models.CharField(default='Our team will reply when available.', max_length=500, validators=[crm.models.validate_plain_text])),
                ('human_handoff_message', models.CharField(default='A team member will continue here.', max_length=500, validators=[crm.models.validate_plain_text])),
                ('privacy_policy_url', models.URLField(blank=True, max_length=500)),
                ('terms_url', models.URLField(blank=True, max_length=500)),
                ('consent_text', models.CharField(default='I agree that this conversation may be stored to provide support.', max_length=1000, validators=[crm.models.validate_plain_text])),
                ('consent_version', models.CharField(default='1', max_length=40, validators=[crm.models.validate_plain_text])),
                ('require_consent', models.BooleanField(default=True)),
                ('require_prechat_form', models.BooleanField(default=False)),
                ('collect_name', models.BooleanField(default=True)),
                ('collect_email', models.BooleanField(default=False)),
                ('collect_phone', models.BooleanField(default=False)),
                ('default_language', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ'), ('en', 'EN')], default='ru', max_length=2)),
                ('supported_languages', models.JSONField(default=web_chat.models.default_languages)),
                ('allowed_origins', models.JSONField(default=list)),
                ('theme_config', models.JSONField(default=web_chat.models.default_theme, validators=[crm.models.validate_safe_metadata])),
                ('ai_mode', models.CharField(choices=[('manual', 'Manual'), ('suggest', 'Suggest'), ('autopilot', 'Autopilot')], default='manual', max_length=20)),
                ('retention_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('production_approved', models.BooleanField(default=False, editable=False)),
                ('live_ai_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='web_chat_installation', to='channels.channelconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_chat_installations_created', to='organizations.organizationmembership')),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_chat_installations', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_chat_installations_updated', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebChatKeyRotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_key_hash', models.CharField(editable=False, max_length=64)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_rotations', to='web_chat.webchatinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('rotated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_chat_key_rotations', to='organizations.organizationmembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('handed_off', 'Handed off'), ('closed', 'Closed'), ('expired', 'Expired'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=20)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(blank=True, max_length=40)),
                ('language', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ'), ('en', 'EN')], max_length=2)),
                ('origin', models.CharField(max_length=255)),
                ('ip_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('abuse_score', models.PositiveSmallIntegerField(default=0)),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_chat_sessions', to='crm.contact')),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_chat_session', to='crm.conversation')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='web_chat.webchatinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebChatMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('safe_category', models.CharField(blank=True, max_length=80)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='web_chat.webchatinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='web_chat.webchatsession')),
            ],
        ),
        migrations.CreateModel(
            name='WebChatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('safe_payload', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('client_event_key', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_chat_events', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web_chat.webchatsession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='webchatinstallation',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='web_chat_we_organiz_19753c_idx'),
        ),
        migrations.AddIndex(
            model_name='webchatkeyrotation',
            index=models.Index(fields=['organization'], name='web_chat_we_organiz_be687f_idx'),
        ),
        migrations.AddIndex(
            model_name='webchatsession',
            index=models.Index(fields=['organization', 'status', '-started_at'], name='web_chat_we_organiz_a2b569_idx'),
        ),
        migrations.AddIndex(
            model_name='webchatsession',
            index=models.Index(fields=['installation', 'status', 'expires_at'], name='web_chat_we_install_31e277_idx'),
        ),
        migrations.AddIndex(
            model_name='webchatmetric',
            index=models.Index(fields=['organization', 'event_type', '-occurred_at'], name='web_chat_we_organiz_5b8805_idx'),
        ),
        migrations.AddIndex(
            model_name='webchatevent',
            index=models.Index(fields=['session', 'sequence'], name='web_chat_we_session_af12c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='webchatevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_web_chat_session_sequence'),
        ),
        migrations.AddConstraint(
            model_name='webchatevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_key', ''), _negated=True), fields=('session', 'client_event_key'), name='unique_web_chat_client_event'),
        ),
    ]
