# Generated by Django 5.2 on 2026-08-11 11:44

import crm.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0006_alter_conversation_ai_state'),
        ('organizations', '0002_branch_working_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramManagerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_id', models.BigIntegerField(unique=True)),
                ('update_type', models.CharField(max_length=40)),
                ('normalized_payload', models.JSONField(default=dict, validators=[crm.models.validate_safe_metadata])),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='received', max_length=20)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramManagedBotRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_telegram_user_id', models.BigIntegerField(db_index=True)),
                ('suggested_username', models.CharField(max_length=32, validators=[crm.models.validate_plain_text])),
                ('suggested_name', models.CharField(max_length=64, validators=[crm.models.validate_plain_text])),
                ('request_nonce_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_user_confirmation', 'Awaiting user confirmation'), ('created', 'Created'), ('token_received', 'Token received'), ('webhook_configured', 'Webhook configured'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_bot_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_bot_username', models.CharField(blank=True, max_length=64, validators=[crm.models.validate_plain_text])),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_managed_requests', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBotConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('managed', 'Managed'), ('existing', 'Existing')], max_length=16)),
                ('bot_user_id', models.BigIntegerField(db_index=True)),
                ('bot_username', models.CharField(max_length=64, validators=[crm.models.validate_plain_text])),
                ('bot_name', models.CharField(max_length=64, validators=[crm.models.validate_plain_text])),
                ('owner_telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('manager_bot_user_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_creation', 'Awaiting creation'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('token_invalid', 'Token invalid'), ('webhook_error', 'Webhook error'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('disconnected', 'Disconnected')], db_index=True, default='draft', max_length=24)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('webhook_public_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('webhook_status', models.CharField(default='pending', max_length=24)),
                ('allowed_updates', models.JSONField(default=list)),
                ('access_restricted', models.BooleanField(default=False)),
                ('permitted_telegram_user_ids', models.JSONField(blank=True, default=list)),
                ('default_language', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ'), ('en', 'EN')], default='ru', max_length=2)),
                ('supported_languages', models.JSONField(default=list)),
                ('privacy_url', models.URLField(blank=True, max_length=500)),
                ('automation_mode', models.CharField(choices=[('manual', 'Manual'), ('suggest', 'Suggest'), ('autopilot', 'Autopilot')], default='manual', max_length=16)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('last_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_connection', to='channels.channelconnection')),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_connections_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('managed_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection', to='telegram.telegrammanagedbotrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('metadata', models.JSONField(default=dict, validators=[crm.models.validate_safe_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='telegram.telegrambotconnection')),
                ('managed_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='telegram.telegrammanagedbotrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramOutboundAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='queued', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_attempts', to='telegram.telegrambotconnection')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_outbound_attempt', to='crm.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUserLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64, validators=[crm.models.validate_plain_text])),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_id', models.BigIntegerField()),
                ('update_type', models.CharField(db_index=True, max_length=40)),
                ('normalized_payload', models.JSONField(default=dict, validators=[crm.models.validate_safe_metadata])),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='received', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='telegram.telegrambotconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegrammanagedbotrequest',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='telegram_te_organiz_7cbc98_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegrambotconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['revoked', 'disconnected']), _negated=True), fields=('bot_user_id',), name='unique_active_telegram_bot'),
        ),
        migrations.AddConstraint(
            model_name='telegrambotconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['revoked', 'disconnected']), _negated=True), fields=('organization',), name='one_active_telegram_bot_per_org'),
        ),
        migrations.AddIndex(
            model_name='telegramoutboundattempt',
            index=models.Index(fields=['organization'], name='telegram_te_organiz_1436db_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramuserlink',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'linked')), fields=('telegram_user_id',), name='unique_linked_telegram_user'),
        ),
        migrations.AddIndex(
            model_name='telegramwebhookevent',
            index=models.Index(fields=['organization', 'status', '-received_at'], name='telegram_te_organiz_3059f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramwebhookevent',
            constraint=models.UniqueConstraint(fields=('connection', 'update_id'), name='unique_telegram_update_per_bot'),
        ),
    ]
