# Generated by Django 5.2 on 2026-08-09 21:59

import crm.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200, validators=[crm.models.validate_plain_text])),
                ('first_name', models.CharField(blank=True, max_length=100, validators=[crm.models.validate_plain_text])),
                ('last_name', models.CharField(blank=True, max_length=100, validators=[crm.models.validate_plain_text])),
                ('company_name', models.CharField(blank=True, max_length=200, validators=[crm.models.validate_plain_text])),
                ('preferred_language', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ'), ('en', 'EN')], default='ru', max_length=2)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('notes_summary', models.TextField(blank=True, max_length=2000, validators=[crm.models.validate_plain_text])),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts_created', to='organizations.organizationmembership')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_contacts', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts_updated', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ['-updated_at', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=5000, validators=[crm.models.validate_plain_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_notes', to='organizations.organizationmembership')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(db_index=True, max_length=20)),
                ('external_thread_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('assignment_state', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned')], db_index=True, default='unassigned', max_length=20)),
                ('automation_state', models.CharField(choices=[('manual', 'Manual'), ('ai_paused', 'AI paused'), ('ai_available', 'AI available')], default='manual', max_length=20)),
                ('handoff_reason', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=300, validators=[crm.models.validate_plain_text])),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to='organizations.organizationmembership')),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='channels.channelconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('last_message_at'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('contact_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('task_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('summary', models.CharField(max_length=500, validators=[crm.models.validate_plain_text])),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_channel_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200, validators=[crm.models.validate_plain_text])),
                ('description', models.TextField(blank=True, max_length=5000, validators=[crm.models.validate_plain_text])),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('archived', 'Archived')], db_index=True, default='open', max_length=20)),
                ('lost_reason', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='organizations.organizationmembership')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.conversation')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_updated', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, validators=[crm.models.validate_plain_text])),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to='organizations.organizationmembership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('related_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact')),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.conversation')),
                ('related_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('system', 'System')], max_length=20)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System'), ('future_ai', 'Future AI')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('note', 'Note'), ('event', 'Event')], default='text', max_length=20)),
                ('body', models.TextField(max_length=10000, validators=[crm.models.validate_plain_text])),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='channels.channelconnection')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='crm.message')),
                ('sender_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, validators=[crm.models.validate_plain_text])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.pipeline'),
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[crm.models.validate_plain_text])),
                ('position', models.PositiveSmallIntegerField()),
                ('color_token', models.CharField(default='green', max_length=30)),
                ('stage_type', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.pipelinestage'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, validators=[crm.models.validate_plain_text])),
                ('color_token', models.CharField(default='green', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='crm.tag')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(related_name='contacts', through='crm.ContactTag', to='crm.tag'),
        ),
        migrations.CreateModel(
            name='ContactIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web_chat', 'Web chat'), ('external', 'External')], db_index=True, max_length=20)),
                ('raw_value', models.CharField(max_length=320, validators=[crm.models.validate_plain_text])),
                ('normalized_value', models.CharField(db_index=True, editable=False, max_length=320)),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_safe_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_identities', to='channels.channelconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['-is_primary', 'type', 'normalized_value'],
                'indexes': [models.Index(fields=['organization', 'type', 'normalized_value'], name='crm_contact_organiz_f4ebb3_idx'), models.Index(fields=['organization', 'channel_connection', 'external_user_id'], name='crm_contact_organiz_ce5f97_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('channel_connection__isnull', False)), fields=('organization', 'type', 'normalized_value', 'channel_connection'), name='unique_org_connected_identity'), models.UniqueConstraint(condition=models.Q(('channel_connection__isnull', True)), fields=('organization', 'type', 'normalized_value'), name='unique_org_unconnected_identity')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'status', '-last_message_at'], name='crm_convers_organiz_1d58f7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'assigned_membership', '-last_message_at'], name='crm_convers_organiz_36a406_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'channel_type', '-last_message_at'], name='crm_convers_organiz_52d38a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'contact', '-last_message_at'], name='crm_convers_organiz_4725a9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'priority', '-last_message_at'], name='crm_convers_organiz_80e1d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('organization', 'channel_connection', 'external_thread_id'), name='unique_org_external_conversation'),
        ),
        migrations.AddIndex(
            model_name='crmactivity',
            index=models.Index(fields=['organization', '-created_at', 'event_type'], name='crm_crmacti_organiz_352acd_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['organization', 'status', 'due_at'], name='crm_followu_organiz_8f4089_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['organization', 'assigned_membership', 'status', 'due_at'], name='crm_followu_organiz_e39926_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization', 'conversation', '-occurred_at'], name='crm_message_organiz_379123_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization', 'status', '-occurred_at'], name='crm_message_organiz_03241e_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id__isnull', False)), fields=('organization', 'channel_connection', 'provider_message_id'), name='unique_org_provider_message'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('organization', 'conversation', 'client_message_id'), name='unique_org_client_message'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_pipeline_name'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='one_default_pipeline_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'position'), name='unique_pipeline_stage_position'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='unique_pipeline_stage_name'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status', 'pipeline', 'stage'], name='crm_lead_organiz_284101_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'assigned_membership', 'status'], name='crm_lead_organiz_d9a27b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'contact', 'status'], name='crm_lead_organiz_ba162c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'next_follow_up_at'], name='crm_lead_organiz_81daab_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('contact', 'tag'), name='unique_contact_tag'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='crm_contact_organiz_8c7a17_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'display_name'], name='crm_contact_organiz_cef476_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'created_at'], name='crm_contact_organiz_187aef_idx'),
        ),
    ]
