# Generated by Django 5.2 on 2026-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_seed_default_pipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_state',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('paused_by_human', 'Paused by human'), ('handoff_required', 'Handoff required')], db_index=True, default='off', max_length=24),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_state_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System'), ('future_ai', 'Future AI'), ('ai', 'AI')], max_length=20),
        ),
    ]
