# Generated by Django 5.2 on 2026-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_conversation_ai_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ai_state',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot'), ('autopilot_instagram', 'Instagram autopilot'), ('paused_by_human', 'Paused by human'), ('handoff_required', 'Handoff required')], db_index=True, default='off', max_length=24),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('note', 'Note'), ('event', 'Event'), ('media', 'Media')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received'), ('read', 'Read')], max_length=20),
        ),
    ]
