# Generated by Django 5.2 on 2026-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_conversation_ai_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ai_state',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot'), ('autopilot_instagram', 'Instagram autopilot'), ('autopilot_telegram', 'Telegram autopilot'), ('paused_by_human', 'Paused by human'), ('handoff_required', 'Handoff required')], db_index=True, default='off', max_length=24),
        ),
    ]
