# Generated by Django 5.2 on 2026-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_conversation_ai_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ai_state',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest'), ('autopilot_test', 'Internal test autopilot'), ('autopilot_web_chat', 'Web Chat autopilot'), ('autopilot_instagram', 'Instagram autopilot'), ('autopilot_telegram', 'Telegram autopilot'), ('autopilot_gmail', 'Gmail autopilot'), ('autopilot_sms', 'SMS autopilot'), ('paused_by_human', 'Paused by human'), ('handoff_required', 'Handoff required')], db_index=True, default='off', max_length=24),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('received', 'Received'), ('read', 'Read')], max_length=20),
        ),
    ]
