# Generated by Django 5.2 on 2026-03-23 12:08

import core.utils.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='phone')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form'), ('manual', 'Manual Entry')], default='sms', max_length=20, verbose_name='source')),
                ('notes', core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form')], db_index=True, max_length=20, verbose_name='channel')),
                ('category', models.CharField(choices=[('immediate_resolution', 'Immediate Resolution'), ('job_request_intake', 'Job Request Intake'), ('review_required', 'Review Required')], db_index=True, default='review_required', max_length=40, verbose_name='category / route')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('review_required', 'Review Required'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=30, verbose_name='status')),
                ('summary', core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='summary')),
                ('raw_content', core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='raw content')),
                ('raw_content_reference', models.CharField(blank=True, max_length=500, verbose_name='raw content reference')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='provider payload')),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='provider ID')),
                ('caller_phone', models.CharField(blank=True, max_length=30, verbose_name='sender phone')),
                ('caller_email', models.CharField(blank=True, max_length=254, verbose_name='sender email')),
                ('classification_confidence', models.FloatField(blank=True, null=True, verbose_name='classification confidence')),
                ('classification_reason', models.CharField(blank=True, max_length=500, verbose_name='classification reason')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='intake.contact', verbose_name='contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form')], max_length=20, verbose_name='source channel')),
                ('service_type', models.CharField(blank=True, max_length=255, verbose_name='service type')),
                ('builder', models.CharField(blank=True, max_length=255, verbose_name='builder')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='project')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='site')),
                ('community', models.CharField(blank=True, max_length=255, verbose_name='community')),
                ('scope', core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='scope / description')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='quantity')),
                ('urgency_notes', models.CharField(blank=True, max_length=500, verbose_name='urgency / deadline notes')),
                ('division', models.CharField(blank=True, max_length=255, verbose_name='division / routing context')),
                ('po_rec_note', models.CharField(blank=True, max_length=500, verbose_name='PO / REC awareness note')),
                ('summary', core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='summary / notes')),
                ('ai_summary', core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='AI / system summary')),
                ('status', models.CharField(choices=[('new', 'New'), ('pending_review', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=30, verbose_name='status')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_records', to='intake.contact', verbose_name='contact / requester')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('source_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to='intake.interaction', verbose_name='source interaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Record',
                'verbose_name_plural': 'Job Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', core.utils.encryption.EncryptedTextField(verbose_name='note body')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='intake.interaction', verbose_name='interaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='intake.jobrecord', verbose_name='job record')),
            ],
            options={
                'verbose_name': 'Internal Note',
                'verbose_name_plural': 'Internal Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='intake.jobrecord', verbose_name='related job'),
        ),
    ]
