# Generated by Django 5.2 on 2026-03-27 07:08

import core.utils.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='assignment_notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='assignment notes'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='completion_notes',
            field=core.utils.encryption.EncryptedTextField(blank=True, default='', verbose_name='completion notes'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='po_required',
            field=models.BooleanField(default=False, verbose_name='PO required'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='po_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('received', 'Received'), ('missing', 'Missing')], db_index=True, default='not_required', max_length=20, verbose_name='PO status'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='rec_required',
            field=models.BooleanField(default=False, verbose_name='REC required'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='rec_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('received', 'Received'), ('missing', 'Missing')], db_index=True, default='not_required', max_length=20, verbose_name='REC status'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last reopened at'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0, verbose_name='reopen count'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='scheduled date'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='scheduled time'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form'), ('manual', 'Manual Entry')], db_index=True, max_length=20, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='po_rec_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='PO / REC note'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='source_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form'), ('manual', 'Manual Entry')], max_length=20, verbose_name='source channel'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending_review', 'Pending Review'), ('prioritized', 'Prioritized'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('blocked', 'Blocked'), ('pending_follow_up', 'Pending Follow-Up'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=30, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('unscheduled', 'Unscheduled'), ('reopened', 'Reopened'), ('po_rec_updated', 'PO/REC Updated'), ('note_added', 'Note Added'), ('assigned', 'Assigned'), ('field_updated', 'Field Updated')], max_length=30, verbose_name='event type')),
                ('old_value', models.CharField(blank=True, max_length=500, verbose_name='old value')),
                ('new_value', models.CharField(blank=True, max_length=500, verbose_name='new value')),
                ('note', models.CharField(blank=True, max_length=1000, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intake.jobrecord', verbose_name='job record')),
            ],
            options={
                'verbose_name': 'Job Event',
                'verbose_name_plural': 'Job Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', core.utils.encryption.EncryptedTextField(verbose_name='note body')),
                ('is_follow_up', models.BooleanField(default=False, verbose_name='is follow-up')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notes', to='intake.jobrecord', verbose_name='job record')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Note',
                'verbose_name_plural': 'Job Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
