# Generated by Django 5.1.4 on 2026-03-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_jobrecord_assigned_to_jobrecord_assignment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('unscheduled', 'Unscheduled'), ('reopened', 'Reopened'), ('po_rec_updated', 'PO/REC Updated'), ('note_added', 'Note Added'), ('assigned', 'Assigned'), ('field_updated', 'Field Updated'), ('urgent_flagged', 'Urgent Alert'), ('missing_auth_flagged', 'Missing Auth Alert')], max_length=30, verbose_name='event type'),
        ),
    ]
