# Generated by Django 5.1.4 on 2026-04-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_alter_jobevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form'), ('manual', 'Manual Entry'), ('voice', 'Voice / Phone Call')], default='sms', max_length=20, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form'), ('manual', 'Manual Entry'), ('voice', 'Voice / Phone Call')], db_index=True, max_length=20, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='source_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email / Form'), ('manual', 'Manual Entry'), ('voice', 'Voice / Phone Call')], max_length=20, verbose_name='source channel'),
        ),
    ]
