# Generated by Django 5.1.4 on 2026-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_alter_contact_source_alter_interaction_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identifier used in code, e.g. "email_short_summary". Do not change once deployed.', max_length=100, unique=True, verbose_name='key')),
                ('text', models.TextField(help_text='Full prompt. Use {text} as the placeholder for the incoming message. Example: "Summarise in 3-4 words: {text}"', verbose_name='prompt text')),
                ('description', models.CharField(blank=True, help_text='Human-readable note for staff — what this prompt is used for.', max_length=500, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompts',
            },
        ),
    ]
