# Generated by Django 5.1.4 on 2026-04-16 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_seed_default_systemprompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text='Short category label, e.g. "Hours", "Pricing", "Warranty".', max_length=255, verbose_name='topic')),
                ('question', models.TextField(help_text='Example question or phrase that should match this entry.', verbose_name='question / trigger')),
                ('answer', models.TextField(help_text='The prepared answer the AI or staff will use.', verbose_name='answer')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords to help retrieval, e.g. "hours,schedule,open".', max_length=500, verbose_name='tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base',
                'ordering': ['topic', 'question'],
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='escalation_reason',
            field=models.CharField(blank=True, help_text='Why this was escalated — filled automatically or by staff.', max_length=500, verbose_name='escalation reason'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Staff has acknowledged this escalation / review item.', verbose_name='read / acknowledged'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='category',
            field=models.CharField(choices=[('immediate_resolution', 'Immediate Resolution'), ('job_request_intake', 'Job Request Intake'), ('review_required', 'Review Required'), ('escalation', 'Escalation')], db_index=True, default='review_required', max_length=40, verbose_name='category / route'),
        ),
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='phone')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='last message at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_job', models.ForeignKey(blank=True, help_text='The JobRecord currently being filled by this thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_threads', to='intake.jobrecord')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_threads', to='intake.contact')),
            ],
            options={
                'verbose_name': 'Conversation Thread',
                'verbose_name_plural': 'Conversation Threads',
                'ordering': ['-last_message_at'],
            },
        ),
    ]
