# Generated by Django 5.1.4 on 2026-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_add_escalation_kb_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationthread',
            name='awaiting_field',
            field=models.CharField(blank=True, help_text='The field the AI last asked about, if any.', max_length=50, verbose_name='awaiting field'),
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='collected_data',
            field=models.JSONField(blank=True, default=dict, help_text='Fields gathered from the SMS dialog before a JobRecord is created (name, service_type, site, scope, email, etc.).', verbose_name='collected data'),
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='state',
            field=models.CharField(choices=[('collecting', 'Collecting info'), ('active', 'Active job'), ('closed', 'Closed')], db_index=True, default='collecting', max_length=20, verbose_name='state'),
        ),
    ]
