# Generated by Django 5.1.4 on 2026-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_thread_state_and_collected_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('unscheduled', 'Unscheduled'), ('reopened', 'Reopened'), ('po_rec_updated', 'PO/REC Updated'), ('note_added', 'Note Added'), ('assigned', 'Assigned'), ('field_updated', 'Field Updated'), ('urgent_flagged', 'Urgent Alert'), ('missing_auth_flagged', 'Missing Auth Alert'), ('message_received', 'Message Received')], max_length=30, verbose_name='event type'),
        ),
    ]
