# Generated by Django 5.2 on 2026-04-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_backfill_short_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='intake.jobrecord', verbose_name='related job'),
        ),
    ]
