# Generated by Django 5.2 on 2026-06-04 14:22

from django.db import migrations, models


def backfill_job_numbers(apps, schema_editor):
    """Assign sequential A-001, A-002 … to existing jobs (oldest first) and
    seed the counter so future allocations continue from there."""
    JobRecord = apps.get_model("intake", "JobRecord")
    JobNumberCounter = apps.get_model("intake", "JobNumberCounter")
    seq = 0
    for job in JobRecord.objects.order_by("created_at", "id"):
        if not job.job_number:
            seq += 1
            job.job_number = f"A-{seq:03d}"
            job.save(update_fields=["job_number"])
    counter, _ = JobNumberCounter.objects.get_or_create(prefix="A")
    if counter.last_value < seq:
        counter.last_value = seq
        counter.save(update_fields=["last_value"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0012_chat_rewrite"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobNumberCounter",
            fields=[
                (
                    "prefix",
                    models.CharField(
                        default="A",
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "last_value",
                    models.PositiveIntegerField(default=0, verbose_name="last value"),
                ),
            ],
            options={
                "verbose_name": "Job Number Counter",
                "verbose_name_plural": "Job Number Counters",
            },
        ),
        # The DB already carries the auto-named index `intake_conv_thread__10eaa8_idx`
        # (created by 0012), but the recorded migration state still calls it
        # `intake_conv_msg_thr_seq`.  Reconcile the *state* only — running the
        # rename as DDL would fail because the old name doesn't exist in the DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="conversationmessage",
                    new_name="intake_conv_thread__10eaa8_idx",
                    old_name="intake_conv_msg_thr_seq",
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="is_seen",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="A staff member has acknowledged this job request.",
                verbose_name="seen / in the works",
            ),
        ),
        # Add job_number plain (no index) first so it applies to existing rows,
        # backfill sequential values, then enforce uniqueness (unique=True adds
        # its own index — keeping db_index too would create a duplicate _like index).
        migrations.AddField(
            model_name="jobrecord",
            name="job_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable tracking ID (e.g. A-001), assigned automatically on creation.",
                max_length=12,
                verbose_name="job number",
            ),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="seen at"),
        ),
        migrations.RunPython(backfill_job_numbers, noop),
        migrations.AlterField(
            model_name="jobrecord",
            name="job_number",
            field=models.CharField(
                blank=True,
                help_text="Human-readable tracking ID (e.g. A-001), assigned automatically on creation.",
                max_length=12,
                unique=True,
                verbose_name="job number",
            ),
        ),
        migrations.AlterField(
            model_name="jobevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status Changed"),
                    ("priority_changed", "Priority Changed"),
                    ("scheduled", "Scheduled"),
                    ("rescheduled", "Rescheduled"),
                    ("unscheduled", "Unscheduled"),
                    ("reopened", "Reopened"),
                    ("po_rec_updated", "PO/REQ Updated"),
                    ("note_added", "Note Added"),
                    ("assigned", "Assigned"),
                    ("field_updated", "Field Updated"),
                    ("urgent_flagged", "Urgent Alert"),
                    ("missing_auth_flagged", "Missing Auth Alert"),
                    ("message_received", "Message Received"),
                ],
                max_length=30,
                verbose_name="event type",
            ),
        ),
        migrations.AlterField(
            model_name="jobrecord",
            name="po_rec_note",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="PO / REQ note"
            ),
        ),
        migrations.AlterField(
            model_name="jobrecord",
            name="rec_required",
            field=models.BooleanField(default=False, verbose_name="REQ required"),
        ),
        migrations.AlterField(
            model_name="jobrecord",
            name="rec_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="not_required",
                max_length=20,
                verbose_name="REQ status",
            ),
        ),
    ]
