# Generated by Django 5.2 on 2026-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0014_backfill_builder_po_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='due date'),
        ),
    ]
