# Generated by Django 5.2 on 2026-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0015_add_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='install_type',
            field=models.CharField(blank=True, help_text='Specific type of install when a job is an "install" request (e.g. silt fence, filter sock, inlet protection).', max_length=255, verbose_name='install type'),
        ),
    ]
