# Generated by Django 5.2 on 2026-06-15 10:03

import uuid
from django.db import migrations, models


def seed_default_leads(apps, schema_editor):
    TeamLead = apps.get_model('intake', 'TeamLead')
    if not TeamLead.objects.exists():
        for i, name in enumerate(['Team Lead 1', 'Team Lead 2', 'Team Lead 3']):
            TeamLead.objects.create(name=name, position=i)


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0016_add_install_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Lead',
                'verbose_name_plural': 'Team Leads',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.RunPython(seed_default_leads, unseed),
    ]
