# Generated by Django 5.2 on 2026-08-09 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('intake', '0020_jobrecord_is_recurring'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='channel_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_threads', to='channels.channelconnection'),
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='channel_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='channels.channelconnection'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='jobevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='jobnote',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='jobnumbercounter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobnumbercounter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='job_number',
            field=models.CharField(blank=True, help_text='Human-readable tracking ID (e.g. A-001), assigned automatically on creation.', max_length=12, verbose_name='job number'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='key',
            field=models.CharField(help_text='Identifier used in code, e.g. "email_short_summary". Do not change once deployed.', max_length=100, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'phone'], name='intake_cont_organiz_7b8388_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='intake_cont_organiz_74ff18_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['organization', 'created_at'], name='intake_conv_organiz_9bf3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['organization', 'phone', 'state', 'is_active'], name='intake_conv_organiz_502dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['organization', 'channel', 'created_at'], name='intake_inte_organiz_5f7514_idx'),
        ),
        migrations.AddIndex(
            model_name='jobevent',
            index=models.Index(fields=['organization', 'created_at'], name='intake_jobe_organiz_9c68dc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecord',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='intake_jobr_organiz_08c7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecord',
            index=models.Index(fields=['organization', 'scheduled_date'], name='intake_jobr_organiz_43431e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['organization', 'is_active', 'topic'], name='intake_know_organiz_fad24e_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_id', ''), _negated=True), fields=('organization', 'channel_connection', 'provider_id'), name='unique_provider_message_per_org_connection'),
        ),
        migrations.AddConstraint(
            model_name='jobnumbercounter',
            constraint=models.UniqueConstraint(fields=('organization', 'prefix'), name='unique_job_counter_org_prefix'),
        ),
        migrations.AddConstraint(
            model_name='jobrecord',
            constraint=models.UniqueConstraint(fields=('organization', 'job_number'), name='unique_job_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='systemprompt',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_system_prompt_key_per_org'),
        ),
        migrations.AddConstraint(
            model_name='teamlead',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_team_lead_name_per_org'),
        ),
    ]
