# Generated by Django 5.2 on 2026-08-09 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def switch_job_counter_primary_key(apps, schema_editor):
    table = "intake_jobnumbercounter"
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(
            """
            CREATE TABLE intake_jobnumbercounter_new (
                id char(32) NOT NULL PRIMARY KEY,
                prefix varchar(4) NOT NULL,
                last_value integer unsigned NOT NULL CHECK (last_value >= 0),
                organization_id char(32) NOT NULL
                    REFERENCES organizations_organization(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT unique_job_counter_org_prefix
                    UNIQUE (organization_id, prefix)
            )
            """
        )
        schema_editor.execute(
            """
            INSERT INTO intake_jobnumbercounter_new (id, prefix, last_value, organization_id)
            SELECT id, prefix, last_value, organization_id FROM intake_jobnumbercounter
            """
        )
        schema_editor.execute("DROP TABLE intake_jobnumbercounter")
        schema_editor.execute(
            "ALTER TABLE intake_jobnumbercounter_new RENAME TO intake_jobnumbercounter"
        )
        schema_editor.execute(
            "CREATE INDEX intake_jobcounter_org_idx "
            "ON intake_jobnumbercounter (organization_id)"
        )
        return

    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{table}_pkey"')
        schema_editor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "id" SET NOT NULL')
        schema_editor.execute(
            f'ALTER TABLE "{table}" ADD CONSTRAINT "{table}_pkey" PRIMARY KEY ("id")'
        )
        return

    raise RuntimeError("Job-number counter primary-key migration supports PostgreSQL and SQLite only.")


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0022_backfill_legacy_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='internalnote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='jobnumbercounter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    switch_job_counter_primary_key,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='jobnumbercounter',
                    name='prefix',
                    field=models.CharField(default='A', max_length=4, verbose_name='prefix'),
                ),
                migrations.AlterField(
                    model_name='jobnumbercounter',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
    ]
