# Generated by Django 5.2 on 2026-08-15 15:21

import booking.models
import crm.models
import django.core.validators
import django.db.models.deletion
import organizations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channelconnection_organization'),
        ('crm', '0008_alter_conversation_ai_state_alter_message_status'),
        ('organizations', '0002_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_reference', models.CharField(default=booking.models.public_reference, editable=False, max_length=40, unique=True)),
                ('service_name_snapshot', models.CharField(max_length=160, validators=[crm.models.validate_plain_text])),
                ('duration_snapshot_minutes', models.PositiveSmallIntegerField()),
                ('price_snapshot_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('currency_snapshot', models.CharField(blank=True, max_length=3, validators=[booking.models.validate_currency])),
                ('source_channel_type', models.CharField(blank=True, db_index=True, max_length=24)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('customer_timezone', models.CharField(max_length=64, validators=[organizations.models.validate_timezone])),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('rejected', 'Rejected')], db_index=True, default='confirmed', max_length=24)),
                ('confirmation_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired')], default='not_required', max_length=16)),
                ('confirmation_token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('confirmation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=1000, validators=[crm.models.validate_plain_text])),
                ('internal_notes', models.TextField(blank=True, max_length=5000, validators=[crm.models.validate_plain_text])),
                ('customer_notes', models.TextField(blank=True, max_length=3000, validators=[crm.models.validate_plain_text])),
                ('created_by_type', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('ai', 'AI'), ('system', 'System')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='organizations.branch')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='crm.contact')),
                ('created_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('primary_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='crm.contactidentity')),
                ('source_channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='channels.channelconnection')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.conversation')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.message')),
            ],
            options={
                'ordering': ['starts_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('expired', 'Expired'), ('released', 'Released')], db_index=True, default='active', max_length=16)),
                ('created_by_type', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('ai', 'AI'), ('system', 'System')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_holds', to='organizations.branch')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_holds', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BookableResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, validators=[crm.models.validate_plain_text])),
                ('resource_type', models.SlugField(max_length=80)),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookable_resources', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='booking.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_links', to='booking.bookableresource')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentHoldResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='booking.appointmenthold')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hold_links', to='booking.bookableresource')),
            ],
        ),
        migrations.AddField(
            model_name='appointmenthold',
            name='resources',
            field=models.ManyToManyField(related_name='holds', through='booking.AppointmentHoldResource', to='booking.bookableresource'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='resources',
            field=models.ManyToManyField(related_name='appointments', through='booking.AppointmentResource', to='booking.bookableresource'),
        ),
        migrations.CreateModel(
            name='BookableStaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160, validators=[crm.models.validate_plain_text])),
                ('timezone_override', models.CharField(blank=True, max_length=64, validators=[organizations.models.validate_timezone])),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('accepts_online_booking', models.BooleanField(default=True)),
                ('maximum_concurrent_appointments', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bookable_profile', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='appointmenthold',
            name='staff_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_holds', to='booking.bookablestaffprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.bookablestaffprofile'),
        ),
        migrations.CreateModel(
            name='PublicBookingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(default=booking.models.public_booking_key, editable=False, max_length=64, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, max_length=160, validators=[crm.models.validate_plain_text])),
                ('intro_text', models.TextField(blank=True, max_length=2000, validators=[crm.models.validate_plain_text])),
                ('privacy_url', models.URLField(blank=True)),
                ('terms_url', models.URLField(blank=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PublicBookingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_sessions', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='booking.publicbookingprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('branch', 'Branch'), ('staff', 'Staff'), ('resource', 'Resource')], max_length=12)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('date', models.DateField(blank=True, null=True)),
                ('start_local_time', models.TimeField()),
                ('end_local_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('branch', 'Branch'), ('staff', 'Staff'), ('resource', 'Resource')], max_length=12)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('exception_type', models.CharField(choices=[('unavailable', 'Unavailable'), ('available_override', 'Available override'), ('holiday', 'Holiday'), ('time_off', 'Time off')], max_length=24)),
                ('reason', models.CharField(blank=True, max_length=500, validators=[crm.models.validate_plain_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_schedule_exceptions', to='organizations.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, validators=[crm.models.validate_plain_text])),
                ('public_description', models.TextField(blank=True, max_length=3000, validators=[crm.models.validate_plain_text])),
                ('internal_description', models.TextField(blank=True, max_length=3000, validators=[crm.models.validate_plain_text])),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('buffer_before_minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(240)])),
                ('buffer_after_minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(240)])),
                ('price_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, validators=[booking.models.validate_currency])),
                ('booking_mode', models.CharField(choices=[('instant', 'Instant'), ('require_confirmation', 'Require confirmation'), ('manual_only', 'Manual only')], default='instant', max_length=24)),
                ('customer_can_choose_staff', models.BooleanField(default=True)),
                ('minimum_notice_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(525600)])),
                ('maximum_advance_days', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(730)])),
                ('cancellation_notice_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(525600)])),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('default_minimum_notice_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(525600)])),
                ('default_maximum_advance_days', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(730)])),
                ('default_cancellation_notice_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(525600)])),
                ('hold_ttl_seconds', models.PositiveSmallIntegerField(default=300, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)])),
                ('allow_customer_reschedule', models.BooleanField(default=True)),
                ('allow_customer_cancel', models.BooleanField(default=True)),
                ('require_email_or_phone', models.BooleanField(default=True)),
                ('require_customer_confirmation', models.BooleanField(default=False)),
                ('auto_confirm_low_risk_actions', models.BooleanField(default=False)),
                ('waitlist_enabled', models.BooleanField(default=True)),
                ('reminder_schedule', models.JSONField(blank=True, default=list)),
                ('reminder_fallback_channels', models.JSONField(blank=True, default=list)),
                ('no_show_policy_text', models.TextField(blank=True, max_length=3000, validators=[crm.models.validate_plain_text])),
                ('cancellation_policy_text', models.TextField(blank=True, max_length=3000, validators=[crm.models.validate_plain_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='booking.service')),
            ],
        ),
        migrations.AddField(
            model_name='appointmenthold',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_holds', to='booking.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.service'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, validators=[crm.models.validate_plain_text])),
                ('description', models.TextField(blank=True, max_length=2000, validators=[crm.models.validate_plain_text])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='booking.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServiceResourceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.SlugField(blank=True, max_length=80)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('required', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='booking.service')),
                ('specific_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requirements', to='booking.bookableresource')),
            ],
        ),
        migrations.CreateModel(
            name='StaffBranchAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='booking.bookablestaffprofile')),
            ],
        ),
        migrations.AddField(
            model_name='bookablestaffprofile',
            name='branches',
            field=models.ManyToManyField(related_name='bookable_staff', through='booking.StaffBranchAssignment', to='organizations.branch'),
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_override_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('price_override_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='booking.service')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_services', to='booking.bookablestaffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earliest_date', models.DateField()),
                ('latest_date', models.DateField()),
                ('preferred_time_windows', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offered', 'Offered'), ('booked', 'Booked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='organizations.branch')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='crm.contact')),
                ('offered_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_offers', to='booking.appointmenthold')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('preferred_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='booking.bookablestaffprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='booking.service')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('branch', 'Branch'), ('staff', 'Staff'), ('resource', 'Resource')], max_length=12)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_local_time', models.TimeField()),
                ('end_local_time', models.TimeField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['owner_type', 'owner_id', 'weekday', 'start_local_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('status_changed', 'Status changed'), ('staff_changed', 'Staff changed'), ('resource_changed', 'Resource changed'), ('reminder_queued', 'Reminder queued'), ('reminder_sent', 'Reminder sent'), ('reminder_failed', 'Reminder failed'), ('customer_replied', 'Customer replied'), ('no_show', 'No show'), ('completed', 'Completed')], db_index=True, max_length=32)),
                ('actor_type', models.CharField(max_length=16)),
                ('summary', models.CharField(max_length=500, validators=[crm.models.validate_plain_text])),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[organizations.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_events', to='organizations.organizationmembership')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['organization', 'appointment', 'created_at'], name='booking_app_organiz_89e165_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('upcoming', 'Upcoming'), ('changed', 'Changed'), ('cancelled', 'Cancelled'), ('waitlist_offer', 'Waitlist offer'), ('follow_up', 'Follow up')], max_length=24)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('preferred_channel', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], db_index=True, default='scheduled', max_length=16)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='booking.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('provider_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_reminders', to='crm.message')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'scheduled_for'], name='booking_app_organiz_8b9595_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='booking_unique_reminder_retry')],
            },
        ),
        migrations.AddIndex(
            model_name='bookableresource',
            index=models.Index(fields=['organization', 'branch', 'resource_type', 'active'], name='booking_boo_organiz_de976e_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookableresource',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('branch', 'name'), name='booking_unique_active_resource'),
        ),
        migrations.AddConstraint(
            model_name='appointmentresource',
            constraint=models.UniqueConstraint(fields=('appointment', 'resource'), name='booking_unique_appointment_resource'),
        ),
        migrations.AddConstraint(
            model_name='appointmentholdresource',
            constraint=models.UniqueConstraint(fields=('hold', 'resource'), name='booking_unique_hold_resource'),
        ),
        migrations.AddConstraint(
            model_name='publicbookingprofile',
            constraint=models.UniqueConstraint(fields=('organization',), name='booking_one_public_profile'),
        ),
        migrations.AddIndex(
            model_name='publicbookingsession',
            index=models.Index(fields=['organization'], name='booking_pub_organiz_21c205_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulebreak',
            index=models.Index(fields=['organization', 'owner_type', 'owner_id', 'date', 'weekday'], name='booking_sch_organiz_9353e6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexception',
            index=models.Index(fields=['organization', 'owner_type', 'owner_id', 'starts_at', 'ends_at'], name='booking_sch_organiz_41436a_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('service__isnull', True)), fields=('organization',), name='booking_one_org_default_policy'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('service__isnull', True)), fields=('organization', 'branch'), name='booking_one_branch_policy'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('service__isnull', False)), fields=('organization', 'service'), name='booking_one_service_policy'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('service__isnull', False)), fields=('organization', 'branch', 'service'), name='booking_one_branch_service_policy'),
        ),
        migrations.AddIndex(
            model_name='appointmenthold',
            index=models.Index(fields=['organization', 'staff_profile', 'starts_at', 'ends_at', 'status'], name='booking_app_organiz_80a759_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenthold',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='booking_app_organiz_b16528_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmenthold',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='booking_unique_hold_retry'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'starts_at', 'status'], name='booking_app_organiz_32bfb1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'staff_profile', 'starts_at', 'ends_at', 'status'], name='booking_app_organiz_fde5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'contact', '-starts_at'], name='booking_app_organiz_6c8669_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='booking_unique_appointment_retry'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('organization', 'name'), name='booking_unique_active_category_name'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'active', 'name'], name='booking_ser_organiz_1b7104_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('organization', 'name'), name='booking_unique_active_service_name'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('price_minor__isnull', True)), ('price_minor__isnull', False), _connector='OR'), name='booking_service_currency_with_price'),
        ),
        migrations.AddConstraint(
            model_name='serviceresourcerequirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resource_type', ''), ('specific_resource__isnull', False)), ('resource_type__gt', ''), _connector='OR'), name='booking_requirement_has_resource_selector'),
        ),
        migrations.AddConstraint(
            model_name='staffbranchassignment',
            constraint=models.UniqueConstraint(fields=('staff_profile', 'branch'), name='booking_unique_staff_branch'),
        ),
        migrations.AddIndex(
            model_name='bookablestaffprofile',
            index=models.Index(fields=['organization', 'active', 'accepts_online_booking'], name='booking_boo_organiz_75909f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffservice',
            index=models.Index(fields=['organization', 'service', 'active'], name='booking_sta_organiz_f6f855_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff_profile', 'service'), name='booking_unique_staff_service'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['organization', 'branch', 'service', 'status', 'earliest_date'], name='booking_wai_organiz_cec58f_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyschedulerule',
            index=models.Index(fields=['organization', 'owner_type', 'owner_id', 'weekday', 'active'], name='booking_wee_organiz_cc9550_idx'),
        ),
    ]
