# Generated by Django 5.2 on 2026-08-09 19:39

import assistant_context.models
import django.db.models.deletion
import organizations.models
import uuid
from django.conf import settings
from django.db import migrations, models


def create_initial_assistant_profiles(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    AssistantProfile = apps.get_model("assistant_context", "OrganizationAssistantProfile")
    AssistantProfile.objects.bulk_create(
        [
            AssistantProfile(
                organization_id=organization.pk,
                supported_languages=[organization.default_language],
                default_language=organization.default_language,
            )
            for organization in Organization.objects.all().iterator()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("organizations", "0002_branch_working_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAssistantProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assistant_name", models.CharField(default="Assistant", max_length=120, validators=[assistant_context.models.validate_plain_text])),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], default="draft", max_length=20)),
                ("business_summary", models.TextField(blank=True, max_length=1000, validators=[assistant_context.models.validate_plain_text])),
                ("business_description", models.TextField(blank=True, max_length=6000, validators=[assistant_context.models.validate_plain_text])),
                ("target_customers", models.TextField(blank=True, max_length=3000, validators=[assistant_context.models.validate_plain_text])),
                ("products_services", models.TextField(blank=True, max_length=6000, validators=[assistant_context.models.validate_plain_text])),
                ("service_area", models.TextField(blank=True, max_length=2000, validators=[assistant_context.models.validate_plain_text])),
                ("supported_languages", models.JSONField(default=assistant_context.models.default_supported_languages, validators=[organizations.models.validate_supported_languages])),
                ("default_language", models.CharField(choices=[("en", "EN"), ("ru", "RU"), ("uz", "UZ")], default="ru", max_length=2)),
                ("tone_of_voice", models.CharField(blank=True, max_length=500, validators=[assistant_context.models.validate_plain_text])),
                ("introduction", models.TextField(blank=True, max_length=2000, validators=[assistant_context.models.validate_plain_text])),
                ("escalation_instructions", models.TextField(blank=True, max_length=5000, validators=[assistant_context.models.validate_plain_text])),
                ("prohibited_topics", models.TextField(blank=True, max_length=4000, validators=[assistant_context.models.validate_plain_text])),
                ("prohibited_actions", models.TextField(blank=True, max_length=4000, validators=[assistant_context.models.validate_plain_text])),
                ("fallback_response", models.TextField(blank=True, max_length=2000, validators=[assistant_context.models.validate_plain_text])),
                ("additional_instructions", models.TextField(blank=True, max_length=6000, validators=[assistant_context.models.validate_plain_text])),
                ("version", models.PositiveIntegerField(default=0)),
                ("published_snapshot", models.JSONField(blank=True, default=dict, editable=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_profile", to="organizations.organization")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assistant_profiles_updated", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AssistantContextRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_context_revisions", to="organizations.organization")),
                ("published_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assistant_context_revisions_published", to=settings.AUTH_USER_MODEL)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="assistant_context.organizationassistantprofile")),
            ],
            options={"ordering": ["-version"]},
        ),
        migrations.RunPython(
            create_initial_assistant_profiles,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="organizationassistantprofile",
            index=models.Index(fields=["organization", "status"], name="assistant_c_organiz_bfcb0d_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantcontextrevision",
            index=models.Index(fields=["organization", "published_at"], name="assistant_c_organiz_67ccf1_idx"),
        ),
        migrations.AddConstraint(
            model_name="assistantcontextrevision",
            constraint=models.UniqueConstraint(fields=("organization", "version"), name="unique_assistant_context_version_per_org"),
        ),
    ]
