# Generated by Django 5.2 on 2026-08-09 19:39

import django.core.validators
import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organizations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="working_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[organizations.models.validate_working_hours],
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="onboarding_completed_steps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="onboarding_current_step",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
